Repository BibliothecaDAO/eternum, pull requests merged in 2024-06, with the labels that each got.

#845 [client] lights update
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#843 feat: Add stamina to action control
  client/src/hooks/helpers/useStamina.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/resources/DepositResources.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/hexagon/ActionInfo.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/utils.tsx
  client/src/ui/elements/ResourceCost.tsx
  client/src/ui/elements/StaminaResource.tsx
  client/src/ui/elements/StaminaResourceCost.tsx
  sdk/packages/eternum/src/constants/global.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#846 Feat/guild
  client/src/dojo/contractComponents.ts
  client/src/dojo/createSystemCalls.ts
  client/src/hooks/helpers/useGuilds.tsx
  client/src/ui/components/navigation/Config.tsx
  client/src/ui/components/worldmap/guilds/GuildInvites.tsx
  client/src/ui/components/worldmap/guilds/GuildMembers.tsx
  client/src/ui/components/worldmap/guilds/Guilds.tsx
  client/src/ui/components/worldmap/guilds/GuildsPanel.tsx
  client/src/ui/components/worldmap/guilds/MyGuild.tsx
  client/src/ui/components/worldmap/guilds/Whitelist.tsx
  client/src/ui/components/worldmap/guilds/utils.tsx
  client/src/ui/modules/guilds/Guilds.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/utils/utils.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/contracts.sh
  contracts/scripts/system_models.json
  contracts/src/models.cairo
  contracts/src/models/guild.cairo
  contracts/src/systems.cairo
  contracts/src/systems/guild/contracts.cairo
  contracts/src/systems/guild/tests.cairo
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4, tests

#847 make food claim automatic
  client/src/ui/components/cityview/realm/SettleRealmComponent.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 3, other

#851 fix: Fix resource already claimed bug in onboarding
  client/src/ui/modules/onboarding/Steps.tsx
Labels: Review effort [1-5]: 2, Bug fix

#860 [client] look updates, bug fixes
  client/public/textures/aura.png
  client/src/hooks/store/_mapStore.tsx
  client/src/hooks/useUISound.tsx
  client/src/types/index.ts
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/hexagon/ActionInfo.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/ui/components/worldmap/hexagon/HoveredHexagon.tsx
  client/src/ui/components/worldmap/hexagon/SelectedUnit.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/modules/scenes/MainScene.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
  client/src/ui/utils/Camera.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#856 Enh/rename entities
  client/src/hooks/helpers/useHyperstructures.tsx
  client/src/hooks/helpers/useShardMines.tsx
  client/src/ui/components/hyperstructures/HyperstructurePanel.tsx
  client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx
  client/src/ui/components/navigation/Config.tsx
  client/src/ui/components/shardMines/ShardMinePanel.tsx
  client/src/ui/components/worldmap/guilds/MyGuild.tsx
  client/src/ui/modules/hyperstructures/Hyperstructures.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/world-structures/WorldStructuresMenu.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/system_models.json
  contracts/src/systems/guild/contracts.cairo
  contracts/src/systems/guild/tests.cairo
  contracts/src/systems/hyperstructure/contracts.cairo
  sdk/packages/eternum/src/constants/global.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#881 Many adjustments
  client/src/hooks/helpers/useExplore.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/containers/BottomMiddleContainer.tsx
  client/src/ui/containers/LoadingContainer.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  client/tailwind.config.js
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 2

#879 Restrict quests on non-realm entities: client + contract + tests
  client/src/ui/modules/navigation/BottomNavigation.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/combat.cairo
  contracts/src/models/realm.cairo
  contracts/src/systems/realm/contracts.cairo
  contracts/src/systems/realm/tests.cairo
Labels: enhancement, Review effort [1-5]: 4, tests

#882 #822
  client/public/images/buildings/thumb/hyperstructure.png
  client/src/dojo/createClientComponents.ts
  client/src/hooks/helpers/useExplore.tsx
  client/src/index.css
  client/src/ui/components/hyperstructures/HyperstructurePanel.tsx
  client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/elements/Button.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#883 [client] UX fixes and improvements
  client/src/ui/components/ModalContainer.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/onboarding/Steps.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#884 sdk chore
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/notifications/generateNotifications.tsx
  client/src/hooks/notifications/useNotifications.tsx
  client/src/ui/components/cityview/BuildingTooltip.tsx
  client/src/ui/components/cityview/regions/FarmsRegionTooltip.tsx
  client/src/ui/components/cityview/regions/FisheryRegionTooltip.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  sdk/packages/eternum/readme.md
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/constants/hex.ts
  sdk/packages/eternum/src/constants/index.ts
  sdk/packages/eternum/src/constants/labor.ts
  sdk/packages/eternum/src/constants/orders.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/constants/structures.ts
  sdk/packages/eternum/src/constants/trade.ts
  sdk/packages/eternum/src/constants/troops.ts
  sdk/packages/eternum/src/types/common.ts
  sdk/packages/eternum/src/types/provider.ts
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, other

#886 update timout
  client/src/hooks/helpers/useExplore.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
Labels: enhancement, Review effort [1-5]: 2, miscellaneous

#885 update combat
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/combat.cairo
  contracts/src/models/config.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#888 Fix stamina on explore
  client/src/hooks/helpers/useGuilds.tsx
  client/src/ui/elements/StaminaResourceCost.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/utils/utils.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#890 optimise path searching + code refactoring
  client/src/hooks/store/_mapStore.tsx
  client/src/types/index.ts
  client/src/ui/components/worldmap/hexagon/ActionInfo.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HoveredHexagon.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/components/worldmap/hexagon/useEventHandlers.tsx
  client/src/ui/components/worldmap/hexagon/utils.tsx
  client/src/ui/utils/utils.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#889 Fixes quest number behind container
  client/src/ui/containers/BottomMiddleContainer.tsx
  client/src/ui/elements/CircleButton.tsx
Labels: Review effort [1-5]: 2, Bug fix

#892 update to 7
  client/.env.production
  client/package.json
  client/src/dojo/setup.ts
  contracts/Scarb.lock
  contracts/Scarb.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/manifests/prod/manifest.json
  contracts/manifests/prod/manifest.toml
  contracts/scripts/env_variables.sh
  contracts/src/models/bank/bank.cairo
  contracts/src/models/bank/liquidity.cairo
  contracts/src/models/bank/market.cairo
  contracts/src/models/buildings.cairo
  contracts/src/models/capacity.cairo
  contracts/src/models/combat.cairo
  contracts/src/models/config.cairo
  contracts/src/models/guild.cairo
  contracts/src/models/hyperstructure.cairo
  contracts/src/models/level.cairo
  contracts/src/models/map.cairo
  contracts/src/models/metadata.cairo
  contracts/src/models/movable.cairo
  contracts/src/models/name.cairo
  contracts/src/models/order.cairo
  contracts/src/models/owner.cairo
  contracts/src/models/population.cairo
  contracts/src/models/position.cairo
  contracts/src/models/production.cairo
  contracts/src/models/quantity.cairo
  contracts/src/models/realm.cairo
  contracts/src/models/resources.cairo
  contracts/src/models/road.cairo
  contracts/src/models/stamina.cairo
  contracts/src/models/structure.cairo
  contracts/src/models/trade.cairo
  contracts/src/models/weight.cairo
  pnpm-lock.yaml
  scripts/contracts.sh
  scripts/deploy.sh
  scripts/indexer.sh
  sdk/packages/eternum/package.json
  sdk/packages/eternum/src/provider/index.ts
Labels: enhancement, Review effort [1-5]: 5, configuration changes

#896 Production optimization
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/production.cairo
Labels: enhancement, Review effort [1-5]: 4

#913 fix: wrong usage of useMemo
  client/src/hooks/store/_mapStore.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
Labels: Review effort [1-5]: 2, Bug fix

#912 contracts: fix internal compiler warnings
  contracts/src/models/buildings.cairo
  contracts/src/models/level.cairo
  contracts/src/models/resources.cairo
  contracts/src/models/road.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/map/tests.cairo
  contracts/src/systems/resources/contracts.cairo
  contracts/src/systems/transport/contracts/donkey_systems.cairo
  contracts/src/systems/transport/contracts/travel_systems.cairo
Labels: Review effort [1-5]: 3, Bug fix

#911 fix: materials depth test rework #861
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/models/biomes/BeachBiome.tsx
  client/src/ui/components/models/biomes/DeciduousForestBiome.tsx
  client/src/ui/components/models/biomes/DeepOceanBiome.tsx
  client/src/ui/components/models/biomes/DesertBiome.tsx
  client/src/ui/components/models/biomes/GrasslandBiome.tsx
  client/src/ui/components/models/biomes/OceanBiome.tsx
  client/src/ui/components/models/biomes/ScorchedBiome.tsx
  client/src/ui/components/models/biomes/ShrublandBiome.tsx
  client/src/ui/components/models/biomes/SnowBiome.tsx
  client/src/ui/components/models/biomes/SubtropicalDesertBiome.tsx
  client/src/ui/components/models/biomes/TaigaBiome.tsx
  client/src/ui/components/models/biomes/TemperateDesertBiome.tsx
  client/src/ui/components/models/biomes/TemperateRainforestBiome.tsx
  client/src/ui/components/models/biomes/TropicalRainforestBiome.tsx
  client/src/ui/components/models/biomes/TropicalSeasonalForestBiome.tsx
  client/src/ui/components/models/biomes/TundraBiome.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/worldmap/Flags.jsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#906 fix: optimistic building of mines #848
  client/src/hooks/helpers/useBuildings.tsx
Labels: Review effort [1-5]: 2, Bug fix

#905 Update dojo version in CI
  .github/workflows/test.yml
Labels: enhancement, Review effort [1-5]: 1

#919 katana: mine block every 3 seconds
  scripts/contracts.sh
Labels: enhancement, Review effort [1-5]: 1

#915 Enh quests popup
  client/src/hooks/helpers/useQuests.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#918 Loaf config
  client/src/ui/components/ModalContainer.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/elements/Headline.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#921 style
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/TroopChip.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/elements/ResourceCost.tsx
  client/src/ui/elements/StaminaResource.tsx
  client/src/ui/layouts/Onboarding.tsx
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/TopLeftNavigation.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: enhancement, Review effort [1-5]: 4, other

#925 Feat/battle model
  client/src/hooks/helpers/useBattles.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/ui/components/models/buildings/worldmap/Battles.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/armies/BattleLabel.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
Labels: enhancement, Review effort [1-5]: 3, tests

#926 Feat/combat raschel
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/store/types.ts
  client/src/hooks/store/useUIStore.tsx
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/models/buildings/worldmap/Battles.tsx
  client/src/ui/components/worldmap/armies/BattleLabel.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#923 Fix trades y overflow + adjust trades header & rows grid
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#922 Fixes quest claim rewards loading state
  client/src/ui/components/hints/HintBox.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#931 fix optimistic travel/explore
  client/src/dojo/createClientComponents.ts
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useTravel.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#927 Battle reward box
  client/src/dojo/contractComponents.ts
  client/src/dojo/createSystemCalls.ts
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/TroopSelect.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/manifests/prod/manifest.json
  contracts/src/constants.cairo
  contracts/src/models/combat.cairo
  contracts/src/models/resources.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/map/tests.cairo
  contracts/src/systems/resources/contracts.cairo
  pnpm-lock.yaml
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4, tests, Bug fix

#933 Fixes notification position + adds armies with moves left notification
  client/src/ui/components/military/EntitiesArmyTable.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#934 feat: add unforeseen cases to combat flow
  client/src/dojo/modelManager/BattleManager.ts
  client/src/hooks/helpers/useBattles.tsx
  client/src/hooks/helpers/useStructures.tsx
  client/src/hooks/store/types.ts
  client/src/hooks/store/useUIStore.tsx
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/military/EntitiesArmyTable.tsx
  client/src/ui/components/models/buildings/worldmap/Battles.tsx
  client/src/ui/components/worldmap/armies/BattleLabel.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
  client/src/ui/modules/military/battle-view/EntityAvatar.tsx
  client/src/ui/modules/military/battle-view/NoOngoingBattle.tsx
  client/src/ui/modules/military/battle-view/OngoingBattle.tsx
  client/src/ui/modules/military/battle-view/Troops.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/combat/contracts.cairo
  sdk/packages/eternum/src/provider/index.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#945 hints bg
  client/src/ui/components/hints/HintModal.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#946 Changed 'waiting to offload' only when at base
  client/src/hooks/helpers/useResources.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/resources/DepositResources.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#948 general fixes and hints
  client/package.json
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/hints/Buildings.tsx
  client/src/ui/components/hints/GettingStarted.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/hints/TheWorld.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/TroopChip.tsx
  client/src/ui/elements/ResourceIcon.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/military/battle-view/NoOngoingBattle.tsx
  client/src/ui/modules/military/battle-view/OngoingBattle.tsx
  client/tailwind.config.js
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/constants.cairo
  pnpm-lock.yaml
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix, Dependencies

#950 Fix guild names UI
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useGuilds.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#951 Fix continue button disabled on acc creation
  client/src/ui/modules/onboarding/Steps.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#953 Fix animation
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyFlag.tsx
  client/src/ui/components/worldmap/armies/ArmyHitBox.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/useArmyAnimation.tsx
  client/src/ui/components/worldmap/armies/utils.tsx
  client/src/ui/components/worldmap/hexagon/utils.tsx
  client/src/ui/elements/BaseThreeTooltip.tsx
  client/src/ui/elements/DojoHtml.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#955 Optimistic stamina
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useStamina.tsx
  client/src/hooks/helpers/useTravel.tsx
Labels: enhancement, Review effort [1-5]: 3

#907 Fix map+realm tests, fixes CI tests
  contracts/src/systems/map/tests.cairo
  contracts/src/systems/realm/tests.cairo
Labels: Review effort [1-5]: 3, tests, Bug fix

#956 Update troop count after battle or pillage
  client/src/dojo/contractComponents.ts
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/utils/utils.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/combat.cairo
  contracts/src/systems/combat/contracts.cairo
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#957 Fix tick
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useStamina.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/ui/components/worldmap/hexagon/useEventHandlers.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#963 fix build
  client/src/dojo/modelManager/types.ts
  client/src/ui/components/hyperstructures/StructureCard.tsx
Labels: Review effort [1-5]: 2, Bug fix

#961 [client] fixes and optimizations
  client/public/models/buildings/bank_lite.glb
  client/public/models/buildings/castle_lite.glb
  client/src/ui/components/models/buildings/worldmap/InstancedBanks.tsx
  client/src/ui/components/models/buildings/worldmap/InstancedCastles.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/worldmap/Flags.jsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/hexagon/UnitHighlight.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/scenes/MainScene.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
  client/src/ui/modules/settings/Settings.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#966 Army sounds
  client/public/sound/units/army_selected1.mp3
  client/public/sound/units/army_selected2.mp3
  client/public/sound/units/army_selected3.mp3
  client/public/sound/units/marching1.mp3
  client/public/sound/units/marching2.mp3
  client/src/hooks/store/_mapStore.tsx
  client/src/hooks/useUISound.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyHitBox.tsx
  client/src/ui/components/worldmap/armies/useArmyAnimation.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HoveredHexagon.tsx
  client/src/ui/components/worldmap/hexagon/useEventHandlers.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#968 prettier fmt
  client/hex/index.html
  client/index.html
  client/map/index.html
  client/src/data/geodata/hex/realmHexPositions.json
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useRoads.tsx
  client/src/index.css
  client/src/ui/components/cityview/realm/trade/DirectOffers/DirectOffersExplorerPopup.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/elements/ListSelect.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
  client/src/ui/modules/military/battle-view/utils.ts
  eternum-docs/docs/pages/development/client.mdx
  eternum-docs/docs/pages/development/contracts.mdx
  eternum-docs/docs/pages/example.mdx
  eternum-docs/docs/pages/game/introduction.mdx
  eternum-docs/docs/pages/getting-started.mdx
  eternum-docs/docs/pages/index.mdx
  eternum-docs/vocs.config.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/constants/resources.ts
Labels: Review effort [1-5]: 2, formatting

#969 Fixes build preview lingering when going from hex -> map view
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: Review effort [1-5]: 2, Bug fix

#972 change naming of fragments, hints, minor tweaks
  client/src/hooks/helpers/useShardMines.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/Combat.tsx
  client/src/ui/components/hints/Guilds.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/hints/Hyperstructures.tsx
  client/src/ui/components/hints/Points.tsx
  client/src/ui/components/hints/TheMap.tsx
  client/src/ui/components/hints/TheWorld.tsx
  client/src/ui/components/hints/Trading.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/models/buildings/worldmap/ShardsMines.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/structures/StructureListItem.tsx
  client/src/ui/elements/StaminaResource.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  contracts/Scarb.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/structure.cairo
  contracts/src/systems/map/contracts.cairo
  pnpm-lock.yaml
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/constants/structures.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#973 fixs #936
  client/hex/index.html
  client/index.html
  client/map/index.html
  client/src/ui/components/hyperstructures/StructureCard.tsx
  scripts/deploy.sh
Labels: enhancement, Review effort [1-5]: 2

#974 [client] labels, bug fixes, light
  client/public/textures/army_label.png
  client/public/textures/hyper_label.png
  client/public/textures/realm_label.png
  client/public/textures/shard_label.png
  client/src/ui/components/models/buildings/worldmap/InstancedCastles.tsx
  client/src/ui/components/models/buildings/worldmap/InstancedLabels.tsx
  client/src/ui/components/models/buildings/worldmap/ShardsMines.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyHitBox.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/modules/scenes/MainScene.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#976 army travel after raiding + hook error
  client/src/hooks/helpers/useStructures.tsx
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/worldmap/armies/useArmyAnimation.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/components/worldmap/hexagon/utils.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#975 Enh/walkthrough
  client/src/hooks/helpers/useQuests.tsx
  client/src/hooks/store/useQuestStore.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/main.tsx
  client/src/ui/components/HooksComponent.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/hints/Resources.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/worldmap/leaderboard/LeaderboardPanel.tsx
  client/src/ui/elements/HintModalButton.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopLeftNavigation.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
Labels: documentation, enhancement, Review effort [1-5]: 4, Bug fix

#977 [client] crash fix, colors update
  client/src/shaders/placeholderMaterial.tsx
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/models/buildings/worldmap/InstancedCastles.tsx
  client/src/ui/components/models/buildings/worldmap/ShardsMines.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/structures/construction/StructurePreview.tsx
  client/src/ui/components/worldmap/Flags.jsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/hexagon/HoveredHexagon.tsx
  client/src/ui/components/worldmap/hexagon/UnitHighlight.tsx
  client/src/ui/modules/scenes/MainScene.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#979 Structure bug
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/cityview/realm/SettleRealmComponent.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#981 Fix army
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyHitBox.tsx
  client/src/ui/components/worldmap/armies/useArmyAnimation.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#980 fix: double click bug
  client/src/ui/components/worldmap/Flags.jsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
Labels: Review effort [1-5]: 2, Bug fix

#978 fix pillage successful bug
  client/src/ui/components/military/Battle.tsx
Labels: Review effort [1-5]: 2, Bug fix

#984 add fixed h
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
Labels: enhancement, Review effort [1-5]: 2

#988 adjust values, improve UX
  client/.env.development
  client/src/hooks/helpers/useTrade.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  sdk/packages/eternum/src/types/common.ts
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#990 Loaf market
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
Labels: enhancement, Review effort [1-5]: 3

#991 fix market button
  client/src/ui/components/trading/MarketOrderPanel.tsx
Labels: Review effort [1-5]: 2, Bug fix

#992 smol fixes and improvements
  client/.env.production
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/layouts/World.tsx
  config/index.ts
  sdk/packages/eternum/src/constants/global.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1003 improve transport management
  client/src/dojo/createSystemCalls.ts
  client/src/hooks/helpers/useResources.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1004 combat styles
  client/src/index.css
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/military/battle-view/Battle.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleDetails.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/military/battle-view/BattleSideView.tsx
  client/src/ui/modules/military/battle-view/EntityAvatar.tsx
  client/src/ui/modules/military/battle-view/LockedResources.tsx
  client/src/ui/modules/military/battle-view/TopScreenView.tsx
  client/src/ui/modules/military/battle-view/Troops.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopLeftNavigation.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/tailwind.config.js
Labels: enhancement, Review effort [1-5]: 4

#1009 fix: uncomment configs
  config/index.ts
Labels: enhancement, Review effort [1-5]: 2

#1010 fix: bug in top middle navigation realms
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: Review effort [1-5]: 2, Bug fix

#1012 market work
  client/hex/index.html
  client/index.html
  client/map/index.html
  client/public/border-22.png
  client/public/border.png
  client/public/images/cover.jpeg
  client/public/images/cover.png
  client/public/images/realm.png
  client/src/hooks/helpers/useArmies.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/elements/TextInput.tsx
  client/src/ui/layouts/Onboarding.tsx
  client/src/ui/modules/LoadingScreen.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1002 feat: Add ongoing costs to clicked buildings
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/containers/BottomMiddleContainer.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
Labels: enhancement, Review effort [1-5]: 3

#1013 fix donkeys check
  client/src/ui/components/trading/MarketOrderPanel.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1011 Change 'prettier' call from write to check
  .github/workflows/lint.yml
  .prettierignore
  client/src/index.css
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#1014 feat: Combat documentation + small style issues + claim logic fix
  client/src/hooks/helpers/useEntities.tsx
  client/src/ui/components/hints/Combat.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyViewCard.tsx
  client/src/ui/components/models/buildings/worldmap/Battles.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/worldmap/realms/RealmListItem.tsx
  client/src/ui/components/worldmap/structures/StructureListItem.tsx
  client/src/ui/containers/BattleContainer.tsx
  client/src/ui/elements/Button.tsx
  client/src/ui/modules/military/battle-view/Battle.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleDetails.tsx
  client/src/ui/modules/military/battle-view/BattleSideView.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
  client/src/ui/modules/military/battle-view/EntityAvatar.tsx
  client/src/ui/modules/military/battle-view/LockedResources.tsx
  client/src/ui/modules/military/battle-view/Troops.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1016 guild work
  client/src/hooks/helpers/useGuilds.tsx
  client/src/ui/components/worldmap/guilds/GuildMembers.tsx
  client/src/ui/components/worldmap/guilds/Guilds.tsx
  client/src/ui/components/worldmap/guilds/MyGuild.tsx
  client/src/ui/elements/SelectBox.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1018 bumps burner to stop deletion
  client/package.json
  client/public/images/background.png
  pnpm-lock.yaml
Labels: Review effort [1-5]: 1, Dependencies

#1020 ux improvements, hints
  client/.env.development
  client/.env.sample
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/Buildings.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/hints/Transport.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/resources/EntityResourceTable.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/components/trading/ResourceArrivals.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/config.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  scripts/indexer.sh
Labels: documentation, enhancement, Review effort [1-5]: 3, Bug fix

#1023 [contracts] Instant AMM
  contracts/src/models/bank/bank.cairo
  contracts/src/models/combat.cairo
  contracts/src/systems/bank/contracts.cairo
  contracts/src/systems/bank/contracts/bank.cairo
  contracts/src/systems/bank/contracts/liquidity.cairo
  contracts/src/systems/bank/contracts/swap.cairo
  contracts/src/systems/bank/tests/bank.cairo
  contracts/src/systems/bank/tests/liquidity.cairo
  contracts/src/systems/bank/tests/swap.cairo
  contracts/src/systems/dev/contracts/bank.cairo
Labels: enhancement, Review effort [1-5]: 4, tests

#1024 feat: Add button for army selection + style fixes
  client/hex/index.html
  client/index.html
  client/map/index.html
  client/src/dojo/modelManager/BattleManager.ts
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/modules/military/battle-view/Battle.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/military/battle-view/BattleSideView.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
  client/src/ui/modules/military/battle-view/EntityAvatar.tsx
  client/src/ui/modules/military/battle-view/LockedResources.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1026 feat: Styling of hex information panel
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/components/worldmap/realms/RealmListItem.tsx
Labels: enhancement, Review effort [1-5]: 3

#1030 dojo 0.7.2
  client/.env.sample
  client/package.json
  contracts/Scarb.lock
  contracts/Scarb.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/bank/contracts/bank.cairo
  contracts/src/systems/bank/contracts/liquidity.cairo
  contracts/src/systems/bank/contracts/swap.cairo
  contracts/src/systems/bank/tests/liquidity.cairo
  contracts/src/systems/bank/tests/swap.cairo
  contracts/src/systems/buildings/contracts.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/dev/contracts/bank.cairo
  contracts/src/systems/dev/contracts/resource.cairo
  contracts/src/systems/guild/contracts.cairo
  contracts/src/systems/hyperstructure/contracts.cairo
  contracts/src/systems/leveling/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  contracts/src/systems/name/contracts.cairo
  contracts/src/systems/realm/contracts.cairo
  contracts/src/systems/resources/contracts.cairo
  contracts/src/systems/trade/contracts/trade_systems.cairo
  contracts/src/systems/transport/contracts/road_systems.cairo
  contracts/src/systems/transport/contracts/travel_systems.cairo
  pnpm-lock.yaml
  scripts/indexer.sh
  sdk/packages/eternum/package.json
Labels: enhancement, Review effort [1-5]: 4, Dependencies

#1021 [client] fixes
  client/src/ui/components/models/buildings/worldmap/Battles.tsx
  client/src/ui/components/models/buildings/worldmap/InstancedCastles.tsx
  client/src/ui/components/models/buildings/worldmap/ShardsMines.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/hexagon/useEventHandlers.tsx
  client/src/ui/utils/Camera.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1031 Loaf fix 4
  client/package.json
  client/src/hooks/helpers/useTrade.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketTradingHistory.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/utils/realms.tsx
  client/src/ui/utils/utils.tsx
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, Dependencies

#1035 fix: battle component changing with getComponentValue
  bot/tsconfig.json
  client/src/dojo/contractComponents.ts
  client/src/dojo/modelManager/BattleManager.ts
  client/src/dojo/modelManager/types.ts
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/hooks/store/useQuestStore.tsx
  client/src/ui/components/military/TroopSelect.tsx
  client/src/ui/layouts/Onboarding.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/military/battle-view/LockedResources.tsx
  client/src/ui/modules/military/battle-view/Troops.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1041 fix error
  client/src/ui/components/military/ArmyList.tsx
Labels: Review effort [1-5]: 1, Bug fix

#1037 Bump dojo version in CI
  .github/workflows/test.yml
Labels: Review effort [1-5]: 1, configuration changes

#1042 add bank model back on world map + change coords
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  config/bank/index.ts
Labels: enhancement, Review effort [1-5]: 2

#1039 feat: battle visual and qol
  client/src/hooks/helpers/useArmies.tsx
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/CombatLabel.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/components/worldmap/realms/RealmListItem.tsx
  client/src/ui/modules/military/battle-view/Battle.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleDetails.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/military/battle-view/EntityAvatar.tsx
  client/src/ui/modules/military/battle-view/LockedResources.tsx
  client/src/ui/modules/military/battle-view/Troops.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1044 set realmEntityId when clicking on structure not owned by us.
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1033 Enh/quests
  client/src/dojo/events/pillageEventQueries.ts
  client/src/hooks/store/useQuestStore.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/structures/construction/StructureCard.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/world-structures/WorldStructuresMenu.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 4, tests

#1045 Fix tests
  .github/workflows/test.yml
  contracts/src/models/resources.cairo
  contracts/src/systems/resources/tests/resource_approval_system_tests.cairo
  contracts/src/systems/resources/tests/resource_transfer_system_tests.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/accept_order.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/cancel_order.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/create_order.cairo
  contracts/src/systems/transport/tests/road_systems_tests.cairo
  contracts/src/systems/transport/tests/travel_systems_tests.cairo
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 4, tests

#1046 Quest resources
  client/src/dojo/createSystemCalls.ts
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/hints/HintBox.tsx
  config/bank/index.ts
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1047 remove food quest
  client/src/hooks/store/useQuestStore.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/provider/index.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1049 Show building cards depending on quests cleared
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
Labels: enhancement, Review effort [1-5]: 2

#1048 prepare prod
  client/.env.production
  config/index.ts
  contracts/Scarb.toml
  contracts/manifests/prod/manifest.json
  contracts/manifests/prod/manifest.toml
  contracts/scripts/env_variables.sh
  scripts/deploy.sh
  sdk/packages/eternum/src/constants/global.ts
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#1054 Fix/hover building
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/hints/HintBox.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1053 mint resources and claim quest in 1 multicall
  client/src/dojo/createSystemCalls.ts
  client/src/ui/components/hints/HintBox.tsx
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 3

#1055 deploy
  .github/workflows/test.yml
  contracts/Scarb.lock
  contracts/Scarb.toml
  contracts/manifests/prod/manifest.json
  contracts/manifests/prod/manifest.toml
  scripts/deploy.sh
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#1056 update reward to fragments
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 2
