Repository BibliothecaDAO/eternum, pull requests merged in 2024-03, with the labels that each got.

#434 init bot
  .github/workflows/pr_agent.yml
Labels: enhancement, Review effort [1-5]: 2

#435 add scripts, cleanup
  client/README.md
  contracts/scripts/set_config.sh
  package.json
  readme.md
  scripts/client.sh
  scripts/contracts.sh
  scripts/indexer.sh
  sdk/readme.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#438 feat: prefetch images
  client/index.html
Labels: enhancement, Review effort [1-5]: 2

#437 remove the Component suffix and rearrage
  client/src/components/ContextComponent.tsx
  client/src/components/SignUpComponent.tsx
  client/src/components/cityview/realm/trade/Market/MarketPanel.tsx
  client/src/components/cityview/realm/trade/Market/OrdersFilter.tsx
  client/src/components/cityview/realm/trade/Market/ResourceFilter.tsx
  client/src/components/navigation/NavigationBubbles.tsx
  client/src/components/navigation/SettingsNavigation.tsx
  client/src/components/notifications/NotificationsComponent.tsx
  client/src/components/worldmap/WorldMap.jsx
  client/src/layouts/World.tsx
  client/src/modules/ContextsModule.tsx
  client/src/modules/NavigationModule.tsx
  client/src/modules/NetworkModule.tsx
  client/src/modules/WorldMapLayersModule.tsx
  client/tsconfig.json
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#440 refactor components
  client/codegen.ts
  client/package.json
  client/src/components/worldmap/Castles.tsx
  client/src/components/worldmap/HexGrid.tsx
  client/src/components/worldmap/WorldMapLayersComponent.tsx
  client/src/components/worldmap/WorldMapMenu.tsx
  client/src/components/worldmap/WorldPopups.tsx
  client/src/components/worldmap/biomes/BeachBiome.tsx
  client/src/components/worldmap/biomes/DeciduousForestBiome.tsx
  client/src/components/worldmap/biomes/DeepOceanBiome.tsx
  client/src/components/worldmap/biomes/DesertBiome.tsx
  client/src/components/worldmap/biomes/GrasslandBiome.tsx
  client/src/components/worldmap/biomes/OceanBiome.tsx
  client/src/components/worldmap/biomes/ScorchedBiome.tsx
  client/src/components/worldmap/biomes/ShrublandBiome.tsx
  client/src/components/worldmap/biomes/SnowBiome.tsx
  client/src/components/worldmap/biomes/SubtropicalDesertBiome.tsx
  client/src/components/worldmap/biomes/TaigaBiome.tsx
  client/src/components/worldmap/biomes/TemperateDesertBiome.tsx
  client/src/components/worldmap/biomes/TemperateRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalSeasonalForestBiome.tsx
  client/src/components/worldmap/biomes/TundraBiome.tsx
  client/src/components/worldmap/hexagon/HexLayers.tsx
  client/src/components/worldmap/hexagon/HexagonGeometry.tsx
  client/src/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/components/worldmap/hexagon/utils.tsx
  client/src/components/worldmap/hyperstructures/Hyperstructures.tsx
  client/src/components/worldmap/realms/RealmListItem.tsx
  client/src/components/worldmap/realms/RealmsListComponent.tsx
  client/src/components/worldmap/realms/RealmsListPanel.tsx
  client/src/components/worldmap/realms/RealmsPositions.tsx
  client/src/generated/graphql.ts
  client/src/graphql/Labor/getRealmLabor.graphql
  client/src/graphql/Labor/getRealmResources.graphql
  client/src/graphql/Realm/getRealm.graphql
  client/src/graphql/Realm/getRealmIds.graphql
  client/src/graphql/Realm/getRealms.graphql
  client/src/graphql/Trade/Trade.fragment.graphql
  client/src/graphql/Trade/getCounterpartyOrderId.graphql
  client/src/graphql/Trade/getIncomingOrderInfo.graphql
  client/src/graphql/Trade/getIncomingOrders.graphql
  client/src/graphql/Trade/getMarket.graphql
  client/src/graphql/Trade/getMyOffers.graphql
  client/src/graphql/Trade/getTradeResources.graphql
  client/src/graphql/Travel/getCaravanInfo.graphql
  client/src/graphql/Travel/getRealmCaravans.graphql
  client/src/hooks/store/_mapStore.tsx
  client/src/layouts/Onboarding.tsx
  client/src/layouts/World.tsx
  client/src/modules/WorldMapMenuModule.tsx
  client/src/modules/scenes/WorldMapScene.tsx
  client/src/types/index.ts
  client/src/utils/utils.tsx
  contracts/scripts/config/generateLevelingCommands.js
  package.json
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#442 feat: level up sound, build farms sound fix
  client/public/sound/ui/level-up.mp3
  client/src/components/cityview/realm/labor/LaborComponent.tsx
  client/src/components/cityview/realm/leveling/LevelingPopup.tsx
  client/src/hooks/useUISound.tsx
Labels: enhancement, Review effort [1-5]: 2

#444 fog of war pass
  client/src/components/worldmap/hexagon/HexLayers.tsx
  client/src/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/components/worldmap/hexagon/utils.tsx
  client/src/modules/scenes/WorldMapScene.tsx
Labels: enhancement, Review effort [1-5]: 3

#445 fix settle hardcoded
  client/src/components/cityview/realm/SettleRealmComponent.tsx
Labels: bug_fix, Review effort [1-5]: 1

#447 menu polishing
  client/.env.sample
  client/src/assets/icons/common/fast-forward.svg
  client/src/components/navigation/NavigationBubbles.tsx
  client/src/components/navigation/SettingsNavigation.tsx
  client/src/components/worldmap/WorldMapMenu.tsx
  client/src/components/worldmap/realms/RealmsListPanel.tsx
  client/src/containers/TopContainer.tsx
  client/src/elements/Avatar.tsx
  client/src/elements/CircleButton.tsx
  client/src/elements/SecondaryPopup.tsx
  client/src/layouts/World.tsx
  client/src/modules/NetworkModule.tsx
  readme.md
  scripts/client.sh
Labels: enhancement, Review effort [1-5]: 4

#449 feat: new army ux
  client/package.json
  client/public/images/blobert.png
  client/public/textures/paper/paper-color.jpg
  client/public/textures/paper/paper-height.jpg
  client/public/textures/paper/paper-normal.jpg
  client/public/textures/paper/paper-roughness.jpg
  client/src/components/worldmap/Castles.tsx
  client/src/components/worldmap/ExploreNotification.tsx
  client/src/components/worldmap/WorldPopups.tsx
  client/src/components/worldmap/armies/Army.tsx
  client/src/components/worldmap/armies/ArmyMenu.tsx
  client/src/components/worldmap/armies/models/WarriorModel.tsx
  client/src/components/worldmap/biomes/BeachBiome.tsx
  client/src/components/worldmap/biomes/DeciduousForestBiome.tsx
  client/src/components/worldmap/biomes/DeepOceanBiome.tsx
  client/src/components/worldmap/biomes/DesertBiome.tsx
  client/src/components/worldmap/biomes/GrasslandBiome.tsx
  client/src/components/worldmap/biomes/OceanBiome.tsx
  client/src/components/worldmap/biomes/ScorchedBiome.tsx
  client/src/components/worldmap/biomes/ShrublandBiome.tsx
  client/src/components/worldmap/biomes/SnowBiome.tsx
  client/src/components/worldmap/biomes/SubtropicalDesertBiome.tsx
  client/src/components/worldmap/biomes/TaigaBiome.tsx
  client/src/components/worldmap/biomes/TemperateDesertBiome.tsx
  client/src/components/worldmap/biomes/TemperateRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalSeasonalForestBiome.tsx
  client/src/components/worldmap/biomes/TundraBiome.tsx
  client/src/components/worldmap/explore/ExploreHexPopup.tsx
  client/src/components/worldmap/hexagon/HexLayers.tsx
  client/src/components/worldmap/hyperstructures/Hyperstructures.tsx
  client/src/elements/ResourceCost.tsx
  client/src/elements/ResourceIcon.tsx
  client/src/elements/SecondaryPopup.tsx
  client/src/geodata/hex/biomes.js
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/hooks/store/useNotificationsStore.tsx
  client/src/index.css
  client/src/modules/WorldMapMenuModule.tsx
  client/src/modules/scenes/WorldMapScene.tsx
  client/tailwind.config.js
  client/tsconfig.json
  pnpm-lock.yaml
  sdk/packages/eternum/src/constants/hex.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#454 fix: images prefetch
  client/map/index.html
  client/realm/index.html
Labels: enhancement, Review effort [1-5]: 2

#458 fix: camera transitions, persistent mute button, popups z-index
  client/src/components/cityview/RealmSwitch.tsx
  client/src/components/cityview/realm/RealmInfoComponent.tsx
  client/src/components/cityview/realm/combat/raids/Raid.tsx
  client/src/components/navigation/NavigationBubbles.tsx
  client/src/elements/SecondaryPopup.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/hooks/useMusic.tsx
  client/src/layouts/World.tsx
  client/src/utils/Camera.tsx
  contracts/manifests/deployments/KATANA.toml
Labels: enhancement, bug_fix, Review effort [1-5]: 5

#459 fix: fixed seeded rotation biomes
  client/src/components/worldmap/biomes/BeachBiome.tsx
  client/src/components/worldmap/biomes/DeciduousForestBiome.tsx
  client/src/components/worldmap/biomes/DeepOceanBiome.tsx
  client/src/components/worldmap/biomes/DesertBiome.tsx
  client/src/components/worldmap/biomes/GrasslandBiome.tsx
  client/src/components/worldmap/biomes/OceanBiome.tsx
  client/src/components/worldmap/biomes/ScorchedBiome.tsx
  client/src/components/worldmap/biomes/ShrublandBiome.tsx
  client/src/components/worldmap/biomes/SnowBiome.tsx
  client/src/components/worldmap/biomes/SubtropicalDesertBiome.tsx
  client/src/components/worldmap/biomes/TaigaBiome.tsx
  client/src/components/worldmap/biomes/TemperateDesertBiome.tsx
  client/src/components/worldmap/biomes/TemperateRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalSeasonalForestBiome.tsx
  client/src/components/worldmap/biomes/TundraBiome.tsx
Labels: enhancement, Review effort [1-5]: 2

#461 fix: no exploration if no food
  client/src/components/worldmap/armies/ArmyMenu.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#464 fix: not show attack if not on realm
  client/src/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx
  client/src/components/cityview/realm/combat/raids/Raid.tsx
  client/src/hooks/helpers/useCombat.tsx
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#466 fix: pillage screen when attacking army
  client/src/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx
Labels: Review effort [1-5]: 2, bug_fix

#470 fix: only 3 hex distance travel
  client/src/components/worldmap/hexagon/utils.tsx
  contracts/scripts/set_config.sh
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#471 feat: new sounds
  client/public/sound/resources/lords.mp3
  client/public/sound/ui/explore.mp3
  client/src/components/worldmap/hexagon/HexLayers.tsx
  client/src/hooks/useUISound.tsx
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#472 fix and refactor attack popup
  client/src/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx
  client/src/components/cityview/realm/combat/raids/RaidsPanel.tsx
  client/src/components/worldmap/Castles.tsx
  client/src/components/worldmap/ChooseArmyActionPopup.tsx
  client/src/components/worldmap/WorldPopups.tsx
  client/src/components/worldmap/explore/ExploreHexPopup.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/hooks/store/useUIStore.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#473 fix: waiting on unsettled realm
  client/src/components/cityview/realm/combat/raids/Raid.tsx
  client/src/hooks/helpers/useRealm.tsx
Labels: enhancement, Review effort [1-5]: 2

#486 feat: unit running sound
  client/src/components/worldmap/armies/models/WarriorModel.tsx
  client/src/components/worldmap/hexagon/HexLayers.tsx
  client/src/hooks/useUISound.tsx
Labels: enhancement, Review effort [1-5]: 3

#477 feat: add toast with error message if tx is reverted
  client/package.json
  client/src/App.tsx
  client/src/dojo/createSystemCalls.ts
  client/src/layouts/World.tsx
  pnpm-lock.yaml
  sdk/packages/eternum/src/provider/index.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4
