Repository BibliothecaDAO/eternum, pull requests merged in 2024-04, with the labels that each got.

#491 feat: highlight hex shape changed to hex edges
  client/src/components/worldmap/hexagon/HexagonGeometry.tsx
  client/src/components/worldmap/hexagon/HighlightedHexes.tsx
Labels: enhancement, Review effort [1-5]: 2

#499 feat: hexception base view
  client/src/components/cityview/hex/BigHexBiome.tsx
  client/src/components/cityview/hex/HexInsideView.tsx
  client/src/components/cityview/realm/RealmBuildingsComponent.tsx
  client/src/components/cityview/realm/RealmCombatComponent.tsx
  client/src/components/cityview/realm/RealmLaborComponent.tsx
  client/src/components/cityview/realm/RealmManagementComponent.tsx
  client/src/components/cityview/realm/RealmTradeComponent.tsx
  client/src/components/cityview/realm/combat/defence/AttacksComponent.tsx
  client/src/components/worldmap/biomes/BeachBiome.tsx
  client/src/components/worldmap/biomes/DeciduousForestBiome.tsx
  client/src/components/worldmap/biomes/DeepOceanBiome.tsx
  client/src/components/worldmap/biomes/DesertBiome.tsx
  client/src/components/worldmap/biomes/GrasslandBiome.tsx
  client/src/components/worldmap/biomes/OceanBiome.tsx
  client/src/components/worldmap/biomes/ScorchedBiome.tsx
  client/src/components/worldmap/biomes/ShrublandBiome.tsx
  client/src/components/worldmap/biomes/SnowBiome.tsx
  client/src/components/worldmap/biomes/SubtropicalDesertBiome.tsx
  client/src/components/worldmap/biomes/TaigaBiome.tsx
  client/src/components/worldmap/biomes/TemperateDesertBiome.tsx
  client/src/components/worldmap/biomes/TemperateRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalRainforestBiome.tsx
  client/src/components/worldmap/biomes/TropicalSeasonalForestBiome.tsx
  client/src/components/worldmap/biomes/TundraBiome.tsx
  client/src/components/worldmap/hexagon/HexLayers.tsx
  client/src/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/modules/scenes/MainScene.tsx
  client/src/modules/scenes/RealmCityViewScene.tsx
  client/src/utils/Camera.tsx
  client/src/utils/utils.tsx
  client/tsconfig.json
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#508 add in bottom menu
  client/src/components/cityview/RealmListBoxes.tsx
  client/src/components/navigation/NavigationBubbles.tsx
  client/src/components/worldmap/hexagon/FixedHexagonInformation.tsx
  client/src/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/containers/LeftMiddleContainer.tsx
  client/src/containers/RightMiddleContainer.tsx
  client/src/modules/BottomNavigation.tsx
  client/src/modules/RightNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 4

#515 feat: build mode
  .gitattributes
  bun.lockb
  client/public/models/buildings/archer_range.glb
  client/public/models/buildings/barracks.glb
  client/public/models/buildings/castle.glb
  client/public/models/buildings/city_tile.glb
  client/public/models/buildings/farm.glb
  client/public/models/buildings/fishery.glb
  client/public/models/buildings/market.glb
  client/public/models/buildings/mine.glb
  client/public/models/buildings/stable.glb
  client/public/models/buildings/storehouse.glb
  client/public/models/buildings/workhut.glb
  client/public/models/city_tile.glb
  client/public/sound/buildings/archer_range.mp3
  client/public/sound/buildings/market.mp3
  client/public/sound/buildings/mine.mp3
  client/public/sound/buildings/stables.mp3
  client/src/components/cityview/RealmListBoxes.tsx
  client/src/components/cityview/hex/HexInsideView.tsx
  client/src/components/cityview/hexception/BigHexBiome.tsx
  client/src/components/cityview/hexception/BuildArea.tsx
  client/src/components/cityview/hexception/GroundGrid.tsx
  client/src/components/cityview/hexception/SelectPreviewBuilding.tsx
  client/src/components/cityview/realm/RealmBuildingsComponent.tsx
  client/src/components/cityview/realm/RealmCombatComponent.tsx
  client/src/components/cityview/realm/RealmLaborComponent.tsx
  client/src/components/cityview/realm/RealmManagementComponent.tsx
  client/src/components/cityview/realm/RealmTradeComponent.tsx
  client/src/components/cityview/realm/combat/defence/AttacksComponent.tsx
  client/src/components/cityview/realm/labor/LaborPanel.tsx
  client/src/hooks/store/_buildModeStore.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/hooks/useUISound.tsx
  client/src/modules/BottomNavigation.tsx
  client/src/modules/scenes/MainScene.tsx
  client/src/modules/scenes/RealmCityViewScene.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#532 resolves #518
  contracts/manifests/dev/abis/base/contracts/eternum_systems_bank_contracts_bank_systems.json
  contracts/manifests/dev/abis/base/models/eternum_models_bank_bank.json
  contracts/manifests/dev/abis/base/models/eternum_models_bank_bank_auction.json
  contracts/manifests/dev/abis/base/models/eternum_models_bank_bank_swap_resource_cost.json
  contracts/manifests/dev/base/contracts/eternum_systems_bank_contracts_bank_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_combat_contracts_combat_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_map_contracts_map_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_realm_contracts_realm_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_resources_contracts_resource_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_travel_systems_travel_systems.toml
  contracts/manifests/dev/base/models/eternum_models_bank_bank.toml
  contracts/manifests/dev/base/models/eternum_models_bank_bank_auction.toml
  contracts/manifests/dev/base/models/eternum_models_bank_bank_swap_resource_cost.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  contracts/src/systems/resources/contracts.cairo
  contracts/src/systems/trade/contracts/trade_systems.cairo
  contracts/src/systems/transport/contracts/travel_systems.cairo
  contracts/target/dev/manifest.json
  contracts/target/release/manifest.json
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#533 fix tests
  contracts/src/systems/bank/tests/bank.cairo
  contracts/src/systems/bank/tests/liquidity.cairo
  contracts/src/systems/bank/tests/swap.cairo
  contracts/src/systems/combat/tests/combat_attack_system_tests.cairo
  contracts/src/systems/combat/tests/combat_steal_system_tests.cairo
  contracts/src/systems/combat/tests/soldier_create_system_tests.cairo
  contracts/src/systems/combat/tests/soldier_detach_system_tests.cairo
  contracts/src/systems/combat/tests/soldier_heal_system_tests.cairo
  contracts/src/systems/combat/tests/soldier_merge_system_tests.cairo
  contracts/src/systems/config/tests/bank_config_tests.cairo
  contracts/src/systems/config/tests/hyperstructure_config_tests.cairo
  contracts/src/systems/config/tests/labor_config_tests/labor_auction_config_tests.cairo
  contracts/src/systems/labor/tests/labor_build_tests.cairo
  contracts/src/systems/labor/tests/labor_harvest_tests.cairo
  contracts/src/systems/labor/tests/labor_purchase_tests.cairo
  contracts/src/systems/leveling/tests/internal_leveling_tests.cairo
  contracts/src/systems/leveling/tests/realm_leveling_tests.cairo
  contracts/src/systems/map/tests.cairo
  contracts/src/systems/realm/tests.cairo
  contracts/src/systems/resources/tests/inventory_transfer_item_system_tests.cairo
  contracts/src/systems/resources/tests/resource_approval_system_tests.cairo
  contracts/src/systems/resources/tests/resource_transfer_system_tests.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/accept_order.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/cancel_order.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/create_order.cairo
  contracts/src/systems/transport/tests/caravan_systems_tests.cairo
  contracts/src/systems/transport/tests/road_systems_tests.cairo
  contracts/src/systems/transport/tests/transport_unit_systems_tests.cairo
  contracts/src/systems/transport/tests/travel_systems_tests.cairo
  contracts/src/utils/testing.cairo
Labels: enhancement, Review effort [1-5]: 2, tests

#539 building placement
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  contracts/.DS_Store
Labels: enhancement, Review effort [1-5]: 3

#543 Building placement
  client/src/dojo/contractComponents.ts
  client/src/dojo/setup.ts
  client/src/hooks/helpers/useQuery.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  contracts/src/models/buildings.cairo
Labels: enhancement, Review effort [1-5]: 2

#547 Cairo chore
  contracts/src/systems.cairo
  contracts/src/systems/bank.cairo
  contracts/src/systems/buildings.cairo
  contracts/src/systems/combat.cairo
  contracts/src/systems/config.cairo
  contracts/src/systems/hyperstructure.cairo
  contracts/src/systems/labor.cairo
  contracts/src/systems/leveling.cairo
  contracts/src/systems/map.cairo
  contracts/src/systems/name.cairo
  contracts/src/systems/realm.cairo
  contracts/src/systems/resources.cairo
  contracts/src/systems/test.cairo
  contracts/src/systems/trade.cairo
  contracts/src/systems/transport.cairo
Labels: enhancement, Review effort [1-5]: 2

#550 contracts: production bug fixes and allow production of only resources available on realm
  contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_combat_contracts_combat_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_hyperstructure_contracts_hyperstructure_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_leveling_contracts_leveling_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_map_contracts_map_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_realm_contracts_realm_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_resources_contracts_resource_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_travel_systems_travel_systems.toml
  contracts/src/models/config.cairo
  contracts/src/models/production.cairo
  contracts/src/models/resources.cairo
  contracts/src/systems/buildings/contracts.cairo
  contracts/src/systems/config/contracts.cairo
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#551 Bug fixes and tests
  contracts/src/models/buildings.cairo
  contracts/src/models/config.cairo
  contracts/src/models/production.cairo
  contracts/src/models/resources.cairo
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#552 feat: optimizations, animations, camera settings
  client/public/models/buildings/farm.glb
  client/src/hooks/helpers/useRealm.tsx
  client/src/hooks/store/_buildModeStore.tsx
  client/src/hooks/useUISound.tsx
  client/src/ui/components/HooksComponent.tsx
  client/src/ui/components/construction/BigHexBiome.tsx
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/layouts/Onboarding.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/modules/scenes/MainScene.tsx
  client/src/ui/utils/Camera.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#555 production bug fix: use accurate end tick
  contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/buildings.cairo
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#556 fix tests
  contracts/src/systems/map/tests.cairo
Labels: enhancement, Review effort [1-5]: 2, tests

#559 feat: construction ux
  client/src/hooks/store/_buildModeStore.tsx
  client/src/shaders/placeholderMaterial.tsx
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/GroundGrid.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#561 production bug fixes
  client/src/dojo/modelManager/ProductionManager.ts
  contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_combat_contracts_combat_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_hyperstructure_contracts_hyperstructure_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_leveling_contracts_leveling_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_map_contracts_map_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_realm_contracts_realm_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_resources_contracts_resource_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.toml
  contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/buildings.cairo
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#566 feat: updated construction menu, worldmap texture, added new sounds
  client/public/images/buildings/construction/archery.png
  client/public/images/buildings/construction/barracks.png
  client/public/images/buildings/construction/farm.png
  client/public/images/buildings/construction/fishing_village.png
  client/public/images/buildings/construction/market.png
  client/public/images/buildings/construction/mine.png
  client/public/images/buildings/construction/stable.png
  client/public/sound/buildings/construction_finish.mp3
  client/public/sound/buildings/sawmill.mp3
  client/public/sound/ui/shovel_1.mp3
  client/public/sound/ui/shovel_2.mp3
  client/src/assets/icons/common/info.svg
  client/src/hooks/useUISound.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/elements/ResourceIcon.tsx
  client/src/ui/elements/Tooltip.tsx
  client/src/ui/modules/construction/Construction.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
Labels: enhancement, Review effort [1-5]: 3

#567 feat: marketplace popup moved to new module
  client/src/assets/icons/common/cross-circle.svg
  client/src/ui/components/cityview/realm/trade/AcceptOffer.tsx
  client/src/ui/components/cityview/realm/trade/FastCreateOffer.tsx
  client/src/ui/components/cityview/realm/trade/Market/MarketPanel.tsx
  client/src/ui/components/cityview/realm/trade/Market/Marketplace.tsx
  client/src/ui/components/navigation/Config.tsx
  client/src/ui/elements/FilterButton.tsx
  client/src/ui/elements/NumberInput.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/modules/trade/Trading.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#578 fix client build errors
  .gitignore
  client/src/dojo/modelManager/BuildingManager.ts
  client/src/dojo/modelManager/types.ts
  client/src/hooks/store/useRealmStore.tsx
  client/src/ui/components/cityview/CityView.tsx
  client/src/ui/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx
  client/src/ui/components/cityview/realm/trade/DirectOffers/DirectOffersExplorerPopup.tsx
  client/src/ui/components/cityview/realm/trade/Market/MarketPanel.tsx
  client/src/ui/components/cityview/realm/trade/MyOffers/MyOffersPanel.tsx
  client/src/ui/components/cityview/regions/FarmsRegionTooltip.tsx
  client/src/ui/components/cityview/regions/FisheryRegionTooltip.tsx
  client/src/ui/components/models/buildings/worldmap/Bank1.tsx
  client/src/ui/components/models/buildings/worldmap/Bank2.tsx
  client/src/ui/components/models/buildings/worldmap/Castles.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  contracts/.DS_Store
  contracts/.gitignore
  contracts/manifests/dev/abis/base/contracts/eternum_systems_buildings_contracts_building_systems.json
  contracts/manifests/dev/abis/base/models/eternum_models_hyperstructure_settlement.json
  contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml
  contracts/manifests/dev/base/models/eternum_models_hyperstructure_settlement.toml
Labels: enhancement, Review effort [1-5]: 3, other

#581 fix: removed unused models
  client/public/models/bastion-transformed.glb
  client/public/models/city_tile.glb
  client/public/models/farms-transformed.glb
  client/public/models/farms.glb
  client/public/models/flags.glb
  client/public/models/hs_lowpoly-transformed.glb
  client/public/models/hs_lowpoly.glb
  client/public/models/hyperstructure-finished-transformed.glb
  client/public/models/hyperstructure-half-transformed.glb
  client/public/models/hyperstructure-started-transformed.glb
  client/public/models/hyperstructure-transformed.glb
  client/public/models/hyperstructure3_half-finished_LOW-transformed.glb
  client/public/models/hyperstructure3_init_LOW-transformed.glb
  client/public/models/realm-buildings-transformed.glb
  client/public/models/realm-city_20-transformed.glb
  client/public/models/realm-landscape-transformed.glb
  client/public/models/unit-transformed.glb
  client/public/models/unit.glb
  client/public/models/warrior.glb
  client/src/ui/components/cityview/CityView.tsx
  client/src/ui/components/cityview/Farms.tsx
  client/src/ui/components/cityview/RealmBuildings.tsx
  client/src/ui/components/cityview/RealmLandscape.tsx
  client/src/ui/components/cityview/realm/RealmBuildingsComponent.tsx
  client/src/ui/components/models/armies/ArmyModel.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/models/buildings/worldmap/Castles.tsx
  client/src/ui/components/worldmap/Flags.jsx
Labels: enhancement, Review effort [1-5]: 3

#582 update tick
  .github/workflows/test.yml
  contracts/src/models/tick.cairo
  eternum-docs/docs/pages/development/contracts.mdx
Labels: documentation, enhancement, Review effort [1-5]: 2

#583 removes unused age model
  contracts/src/models.cairo
  contracts/src/models/age.cairo
  contracts/src/utils/testing.cairo
Labels: enhancement, Review effort [1-5]: 2

#587 feat: new models, transfer UI
  client/public/models/buildings/archer_range.glb
  client/public/models/buildings/barracks.glb
  client/public/models/buildings/castle.glb
  client/public/models/buildings/empty.glb
  client/public/models/buildings/fishery.glb
  client/public/models/buildings/market.glb
  client/public/models/buildings/mine.glb
  client/public/models/buildings/stable.glb
  client/public/models/buildings/storehouse.glb
  client/public/models/buildings/workhut.glb
  client/src/hooks/helpers/useEntities.tsx
  client/src/ui/components/cityview/realm/RealmManagementComponent.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/trading/Marketplace.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/elements/Button.tsx
  client/src/ui/elements/NumberInput.tsx
  client/src/ui/modules/trade/Trading.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#603 feat: new models
  client/public/models/buildings/forge.glb
  client/public/models/buildings/lumber_mill.glb
  client/src/hooks/store/_buildModeStore.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
Labels: enhancement, Review effort [1-5]: 3

#608 fix send resources and add arrivals
  client/src/hooks/helpers/useResources.tsx
  client/src/ui/components/cityview/realm/RealmTradeComponent.tsx
  client/src/ui/components/cityview/realm/trade/MyOffers/MyOffersPanel.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/trading/ResourceArrivals.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/modules/trade/Trading.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#610 add fixed building cost
  contracts/scripts/set_config.sh
  contracts/src/models/buildings.cairo
  contracts/src/models/config.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/config/interface.cairo
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#621 Update compass on rotation
  client/src/ui/components/worldmap/Compass.tsx
  client/src/ui/utils/Camera.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#634 Enforce storehouse limit on resource balance
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/constants.cairo
  contracts/src/models/buildings.cairo
  contracts/src/models/combat.cairo
  contracts/src/models/resources.cairo
  contracts/src/systems/bank/contracts/bank_systems.cairo
  contracts/src/systems/bank/contracts/liquidity_systems.cairo
  contracts/src/systems/bank/contracts/swap_systems.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/dev/contracts/resource.cairo
  contracts/src/systems/leveling/contracts.cairo
  contracts/src/systems/realm/contracts.cairo
  contracts/src/systems/transport/contracts/donkey_systems.cairo
  contracts/src/systems/transport/contracts/road_systems.cairo
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#633 feat: costs UI
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/elements/BaseThreeTooltip.tsx
Labels: enhancement, Review effort [1-5]: 3

#632 selected hex highlight + HoveringContainer
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/types/index.ts
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyPanel.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/HoveringContainer.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/hexagon/FixedHexagonInformation.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx
  client/src/ui/modules/entity-details/EntityDetails.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: enhancement, Review effort [1-5]: 3

#639 fix: hexagon hole, water color
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
Labels: Review effort [1-5]: 2, bug_fix

#638 Optimistic animation paths
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/system_models.json
  contracts/src/systems/transport/contracts/travel_systems.cairo
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#640 Optimistic building
  client/src/dojo/createClientComponents.ts
  client/src/hooks/helpers/useBuildings.tsx
Labels: enhancement, Review effort [1-5]: 3

#641 solves #629 by adding cancel trade
  client/src/ui/components/trading/Marketplace.tsx
Labels: enhancement, Review effort [1-5]: 3

#644 UI fixes
  client/hex/index.html
  client/map/index.html
  client/public/models/buildings/workhut.glb
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/models/buildings/worldmap/Banks.tsx
  client/src/ui/components/worldmap/Compass.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/utils/Camera.tsx
  client/vite.config.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix
