Repository BibliothecaDAO/eternum, pull requests merged in 2024-07, with the labels that each got.

#1059 Enh/hints
  client/src/ui/components/bank/ResourceBar.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/Buildings.tsx
  client/src/ui/components/hints/Combat.tsx
  client/src/ui/components/hints/GettingStarted.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/hints/Hyperstructures.tsx
  client/src/ui/components/hints/Resources.tsx
  client/src/ui/components/hints/TheMap.tsx
  client/src/ui/components/hints/TheWorld.tsx
  client/src/ui/components/hints/Trading.tsx
  client/src/ui/components/hints/Transport.tsx
  client/src/ui/components/hints/WorldStructures.tsx
  client/src/ui/components/hints/utils.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/navigation/Config.tsx
  client/src/ui/components/navigation/OSWindow.tsx
  client/src/ui/components/trading/ResourceArrivals.tsx
  client/src/ui/components/worldmap/leaderboard/LeaderboardPanel.tsx
  client/src/ui/elements/HintModalButton.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/modules/guilds/Guilds.tsx
  client/src/ui/modules/leaderboard/LeaderBoard.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/military/battle-view/Battle.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/world-structures/WorldStructuresMenu.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: documentation, enhancement, Review effort [1-5]: 4

#1067 fix: weights and donkeys
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyPanel.tsx
  client/src/ui/components/resources/DepositResources.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/LockedResources.tsx
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/constants/travel.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1066 [UI] Prevent depositing resources on structures in battle.
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/resources/DepositResources.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1070 Enh/combat hints
  client/src/hooks/helpers/useStamina.tsx
  client/src/ui/components/hints/Combat.tsx
  client/src/ui/components/hints/GettingStarted.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/hints/Resources.tsx
  client/src/ui/components/hints/TheMap.tsx
  client/src/ui/components/hints/TheWorld.tsx
  client/src/ui/components/hints/Trading.tsx
  client/src/ui/components/hints/Transfers.tsx
  client/src/ui/components/hints/Transport.tsx
  client/src/ui/components/hints/WorldStructures.tsx
  client/src/ui/components/hints/utils.tsx
  client/src/ui/components/hyperstructures/StructureCard.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/ArmyViewCard.tsx
  client/src/ui/components/military/TroopChip.tsx
  client/src/ui/components/military/TroopSelect.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/elements/ResourceIcon.tsx
  client/src/ui/modules/military/battle-view/Troops.tsx
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/constants/structures.ts
  sdk/packages/eternum/src/constants/troops.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#1073 Fix/storehouse cap
  client/src/ui/components/hints/Combat.tsx
  client/src/ui/components/hints/Resources.tsx
Labels: enhancement, Review effort [1-5]: 2, formatting

#1069 fix: various small fixes
  client/src/hooks/helpers/useHyperstructures.tsx
  client/src/hooks/helpers/useResources.tsx
  client/src/hooks/helpers/useStructures.tsx
  client/src/hooks/store/useLeaderBoardStore.tsx
  client/src/ui/components/hyperstructures/HyperstructurePanel.tsx
  client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/components/structures/construction/StructurePreview.tsx
  client/src/ui/components/worldmap/structures/StructureListItem.tsx
  client/src/ui/elements/ResourceIcon.tsx
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1082 change hyperstructure completion amounts
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 2

#1081 Fix exploring w/ army owned by structure that isnt a realm
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/map/contracts.cairo
Labels: Review effort [1-5]: 2, Bug fix

#1085 prettier
  client/src/hooks/helpers/useHyperstructures.tsx
Labels: Review effort [1-5]: 1, formatting

#1087 Fix amm ux
  client/src/dojo/modelManager/MarketManager.ts
  client/src/hooks/helpers/useTravel.tsx
  client/src/ui/components/bank/AddLiquidity.tsx
  client/src/ui/components/bank/BankList.tsx
  client/src/ui/components/bank/ConfirmationPopup.tsx
  client/src/ui/components/bank/LiquidityResourceRow.tsx
  client/src/ui/components/bank/LiquidityTable.tsx
  client/src/ui/components/bank/ResourceBar.tsx
  client/src/ui/components/bank/Swap.tsx
  client/src/ui/components/cityview/realm/trade/AcceptOffer.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/trading/Marketplace.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  sdk/packages/eternum/src/constants/global.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1086 fix: army deposits battle bugs + hyperstructure points calculations
  client/src/dojo/modelManager/BattleManager.ts
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/helpers/useBattles.tsx
  client/src/hooks/helpers/useHyperstructures.tsx
  client/src/hooks/helpers/useResources.tsx
  client/src/hooks/store/useLeaderBoardStore.tsx
  client/src/hooks/store/useQuestStore.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/hyperstructures/HyperstructurePanel.tsx
  client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/BattlesArmyTable.tsx
  client/src/ui/components/military/EntitiesArmyTable.tsx
  client/src/ui/components/models/buildings/worldmap/Battles.tsx
  client/src/ui/components/trading/ResourceArrivals.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  contracts/scripts/testing/mint_resource.sh
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1065 feat: add mercenaries
  client/public/images/avatars/mercenary.png
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/helpers/useStructures.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleDetails.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/military/battle-view/EntityAvatar.tsx
  config/index.ts
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/system_models.json
  contracts/src/models/buildings.cairo
  contracts/src/models/config.cairo
  contracts/src/systems/buildings/contracts.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  contracts/src/systems/map/tests.cairo
  contracts/src/utils/testing.cairo
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4, tests

#1058 fix amm liquidity provision
  client/src/dojo/contractComponents.ts
  client/src/dojo/modelManager/MarketManager.ts
  client/src/hooks/helpers/useTravel.tsx
  client/src/ui/components/bank/AddLiquidity.tsx
  client/src/ui/components/bank/BankList.tsx
  client/src/ui/components/bank/ConfirmationPopup.tsx
  client/src/ui/components/bank/LiquidityResourceRow.tsx
  client/src/ui/components/bank/LiquidityTable.tsx
  client/src/ui/components/bank/ResourceBar.tsx
  client/src/ui/components/bank/Swap.tsx
  client/src/ui/components/cityview/realm/trade/AcceptOffer.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/trading/Marketplace.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  config/bank/index.ts
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/bank/bank.cairo
  contracts/src/models/bank/market.cairo
  contracts/src/models/config.cairo
  contracts/src/systems/bank/contracts/bank.cairo
  contracts/src/systems/bank/contracts/swap.cairo
  contracts/src/systems/bank/tests.cairo
  contracts/src/systems/bank/tests/bank.cairo
  contracts/src/systems/bank/tests/liquidity.cairo
  contracts/src/systems/bank/tests/swap.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/dev/contracts/bank.cairo
  pnpm-lock.yaml
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: Review effort [1-5]: 3, tests, Bug fix

#1060 Clean sdk
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/config.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/buildings.cairo
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/constants/structures.ts
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#1089 Fix: transfer to structures not working because of OwnerEntity on position query
  client/src/dojo/createSystemCalls.ts
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/helpers/useBattles.tsx
  client/src/hooks/helpers/useResources.tsx
  client/src/hooks/helpers/useStructures.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/hints/Buildings.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/structures/StructureListItem.tsx
  client/src/ui/modules/military/battle-view/BattleActions.tsx
  client/src/ui/modules/military/battle-view/BattleView.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1091 onboard
  client/.env.production
  client/src/hooks/store/useQuestStore.tsx
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/provider/index.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1095 contracts: fix chest reward bug
  contracts/src/systems/combat/contracts.cairo
  sdk/packages/eternum/src/constants/resources.ts
Labels: Review effort [1-5]: 2, Bug fix

#1106 remove all army labels
  client/src/ui/components/worldmap/armies/ArmyHitBox.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1104 Fix table grid
  client/src/ui/components/bank/LiquidityResourceRow.tsx
  client/src/ui/components/bank/LiquidityTable.tsx
Labels: enhancement, Review effort [1-5]: 3

#1115 Fix/markets
  client/src/ui/components/bank/Swap.tsx
  client/src/ui/components/cityview/realm/trade/Roads/RoadRealmSelector.tsx
  client/src/ui/components/cityview/realm/trade/TradeRealmSelector.tsx
  client/src/ui/components/entities/SelectLocationPanel.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/toggle/ToggleComponent.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/trading/MarketTradingHistory.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1116 Fix/names
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/worldmap/Flags.jsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
Labels: enhancement, Review effort [1-5]: 2

#1118 contracts: disallow join after battle ends
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/combat/contracts.cairo
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1107 remove notifications code
  client/src/hooks/notifications/generateNotifications.tsx
  client/src/hooks/notifications/useBankNotification.tsx
  client/src/hooks/notifications/useCombatNotification.tsx
  client/src/hooks/notifications/useEmptyChestNotification.tsx
  client/src/hooks/notifications/useHarvestNotification.tsx
  client/src/hooks/notifications/useHyperstructureNotification.tsx
  client/src/hooks/notifications/useNotifications.tsx
  client/src/hooks/notifications/useTradeNotification.tsx
  client/src/hooks/notifications/utils.tsx
  client/src/ui/components/notifications/NotificationsComponent.tsx
  client/src/ui/elements/Notification.tsx
Labels: enhancement, Review effort [1-5]: 3, other

#1119 feat: introduce testing configs
  contracts/src/models/combat.cairo
  contracts/src/models/owner.cairo
  contracts/src/models/resources.cairo
  contracts/src/models/road.cairo
  contracts/src/systems/bank/tests/bank.cairo
  contracts/src/systems/bank/tests/liquidity.cairo
  contracts/src/systems/bank/tests/swap.cairo
  contracts/src/systems/config/tests/hyperstructure_config_tests.cairo
  contracts/src/systems/guild/tests.cairo
  contracts/src/systems/hyperstructure/tests.cairo
  contracts/src/systems/leveling/tests/internal_leveling_tests.cairo
  contracts/src/systems/leveling/tests/realm_leveling_tests.cairo
  contracts/src/systems/map/tests.cairo
  contracts/src/systems/realm/tests.cairo
  contracts/src/systems/resources/tests/resource_approval_system_tests.cairo
  contracts/src/systems/resources/tests/resource_transfer_system_tests.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/accept_order.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/cancel_order.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/create_order.cairo
  contracts/src/systems/transport/tests/road_systems_tests.cairo
  contracts/src/systems/transport/tests/travel_systems_tests.cairo
  contracts/src/utils/testing.cairo
  contracts/src/utils/testing/config.cairo
  contracts/src/utils/testing/constants.cairo
  contracts/src/utils/testing/general.cairo
  contracts/src/utils/testing/systems.cairo
  contracts/src/utils/testing/world.cairo
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/provider/index.ts
Labels: enhancement, Review effort [1-5]: 2, tests

#1114 Fix quests rerendering perf
  client/src/hooks/helpers/useQuests.tsx
  client/src/hooks/helpers/useStamina.tsx
  client/src/hooks/store/useQuestStore.tsx
  client/src/ui/components/HooksComponent.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/quest/QuestInfo.tsx
  client/src/ui/components/quest/QuestList.tsx
  client/src/ui/components/quest/QuestPanel.tsx
  client/src/ui/components/quest/questDetails.tsx
  client/src/ui/components/quest/utils.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/world-structures/WorldStructuresMenu.tsx
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1142 fix small ui bugs
  client/src/hooks/helpers/useQuests.tsx
  client/src/ui/components/quest/QuestList.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix
