Repository BibliothecaDAO/eternum, pull requests merged in 2024-05, with the labels that each got.

#645 add new building quantity model
  contracts/src/models/buildings.cairo
  contracts/src/models/resources.cairo
Labels: enhancement, Review effort [1-5]: 3

#646 fix resource config
  client/package.json
  client/src/dojo/contractComponents.ts
  client/src/dojo/createSystemCalls.ts
  client/src/ui/components/cityview/realm/SettleRealmComponent.tsx
  client/src/ui/components/navigation/Config.tsx
  client/src/ui/modules/construction/Construction.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/questing/Questing.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/set_config.sh
  contracts/scripts/system_models.json
  contracts/src/models/config.cairo
  contracts/src/systems.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/realm/contracts.cairo
  contracts/src/systems/realm/interface.cairo
  pnpm-lock.yaml
  scripts/contracts.sh
  sdk/packages/eternum/package.json
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#647 quests-b
  client/src/ui/modules/scenes/MainScene.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/system_models.json
  scripts/contracts.sh
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#650 prod deploy
  client/.env.production
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/modules/scenes/MainScene.tsx
  client/src/ui/utils/Camera.tsx
  contracts/Scarb.toml
  contracts/manifests/prod/manifest.json
  contracts/manifests/prod/manifest.toml
  contracts/scripts/env_variables.sh
  scripts/deploy.sh
Labels: enhancement, bug_fix

#654 config fixes
  client/.env.development
  contracts/scripts/set_config.sh
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#655 fix: scrollable build menu, camera transition
  client/src/hooks/store/useUIStore.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: enhancement, Review effort [1-5]: 2

#662 shards
  client/public/images/buildings/thumb/banks.png
  client/public/images/buildings/thumb/crane.png
  client/public/images/buildings/thumb/leaderboard.png
  client/public/images/buildings/thumb/realm.png
  client/public/images/buildings/thumb/resources.png
  client/public/images/buildings/thumb/squire.png
  client/public/images/buildings/thumb/sword.png
  client/public/images/buildings/thumb/trade.png
  client/public/images/buildings/thumb/world-map.png
  client/public/images/resources/29.png
  client/src/index.css
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/list/RealmListBoxes.tsx
  client/src/ui/containers/BottomMiddleContainer.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/elements/ResourceIcon.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  client/src/ui/modules/questing/Questing.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/constants.cairo
  contracts/src/systems/config/contracts.cairo
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3

#667 Fix banks
  client/src/dojo/contractComponents.ts
  client/src/dojo/createUpdates.ts
  client/src/dojo/events/bankEventQueries.ts
  client/src/dojo/events/createEventSubscription.ts
  client/src/dojo/events/graphqlClient.ts
  client/src/dojo/modelManager/MarketManager.ts
  client/src/dojo/modelManager/types.ts
  client/src/ui/components/bank/AddLiquidity.tsx
  client/src/ui/components/bank/BankList.tsx
  client/src/ui/components/bank/LiquidityResourceRow.tsx
  client/src/ui/components/bank/Swap.tsx
  client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx
  contracts/Scarb.toml
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/set_config.sh
  contracts/scripts/system_models.json
  contracts/src/models/bank/market.cairo
  contracts/src/models/resources.cairo
  contracts/src/systems.cairo
  contracts/src/systems/bank/contracts/bank_systems.cairo
  contracts/src/systems/bank/contracts/liquidity_systems.cairo
  contracts/src/systems/bank/contracts/swap_systems.cairo
  contracts/src/systems/bank/tests/bank.cairo
  contracts/src/systems/bank/tests/liquidity.cairo
  contracts/src/systems/bank/tests/swap.cairo
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#673 speed up donkeys
  contracts/scripts/set_config.sh
Labels: enhancement, Review effort [1-5]: 2

#672 add admin bank with liquidity
  contracts/Scarb.lock
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/contracts.sh
  contracts/scripts/set_admin_bank.sh
  contracts/src/systems/dev/contracts.cairo
  contracts/src/systems/dev/contracts/bank.cairo
Labels: enhancement, Review effort [1-5]: 4, other

#674 ethershards leaderboard
  client/src/hooks/store/useLeaderBoardStore.tsx
  client/src/ui/components/worldmap/leaderboard/LeaderboardPanel.tsx
  client/src/ui/components/worldmap/leaderboard/OrdersLeaderboard.tsx
  client/src/ui/components/worldmap/leaderboard/PlayersLeaderboard.tsx
  client/src/ui/modules/leaderboard/LeaderBoard.tsx
Labels: enhancement, Review effort [1-5]: 3

#677 add in population to top nav
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/set_admin_bank.sh
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#680 solves #669 by reverting explore and travel animation if tx fail
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useTravel.tsx
Labels: Review effort [1-5]: 2, bug_fix

#681 Loaf/edit
  client/public/test-bg.png
  client/src/dojo/contractComponents.ts
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/helpers/useStructures.tsx
  client/src/ui/components/ModalContainer.tsx
  client/src/ui/components/construction/BigHexBiome.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/realms/RealmListItem.tsx
  client/tailwind.config.js
  contracts/scripts/set_admin_bank.sh
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#685 tweaks
  client/src/dojo/modelManager/ProductionManager.ts
  client/src/ui/components/ModalContainer.tsx
Labels: enhancement, Review effort [1-5]: 2

#684 pillage bug fixes
  contracts/scripts/set_config.sh
  contracts/scripts/system_models.json
  contracts/src/systems/combat/contracts.cairo
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#692 Trade time
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/ui/components/HooksComponent.tsx
  client/src/ui/components/bank/BankList.tsx
  client/src/ui/components/cityview/RealmSwitch.tsx
  client/src/ui/components/cityview/realm/trade/AcceptOffer.tsx
  client/src/ui/components/cityview/realm/trade/CreateOffer.tsx
  client/src/ui/components/cityview/realm/trade/FastCreateOffer.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/toggle/ToggleComponent.tsx
  client/src/ui/components/trading/Marketplace.tsx
  client/src/ui/components/trading/SendResourcesPanel.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/modules/trade/Trading.tsx
Labels: enhancement, Review effort [1-5]: 3

#694 Small improvements
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/list/EntityList.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#693 allow only one structure per hex
  contracts/scripts/system_models.json
  contracts/src/models/structure.cairo
  contracts/src/systems/bank/contracts/bank_systems.cairo
  contracts/src/systems/realm/contracts.cairo
Labels: enhancement, Review effort [1-5]: 3

#695 pillage bug fix
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  contracts/src/systems/resources/contracts.cairo
  contracts/src/systems/trade/contracts/trade_systems.cairo
  contracts/src/systems/transport/contracts/donkey_systems.cairo
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#696 destroy building during pillage
  contracts/scripts/system_models.json
  contracts/src/models/buildings.cairo
  contracts/src/models/position.cairo
  contracts/src/systems/combat/contracts.cairo
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#698 Fix lp
  client/src/dojo/modelManager/MarketManager.ts
  client/src/hooks/helpers/useResources.tsx
  client/src/ui/components/bank/LiquidityResourceRow.tsx
  client/src/ui/components/bank/LiquidityTable.tsx
  client/src/ui/components/entities/Entity.tsx
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/types/common.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#700 Pillage result
  client/src/dojo/createUpdates.ts
  client/src/ui/components/military/Battle.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/models/buildings.cairo
  contracts/src/systems/combat/contracts.cairo
  sdk/packages/eternum/src/constants/events.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#704 Performance
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/hexagon/FixedHexagonInformation.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  client/src/ui/utils/Camera.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#708 better building info
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
Labels: enhancement, Review effort [1-5]: 2

#709 hints and walks
  client/public/images/buildings/thumb/question-wood.png
  client/src/hooks/helpers/useRealm.tsx
  client/src/main.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/HintModal.tsx
  client/src/ui/components/list/RealmListBoxes.tsx
  client/src/ui/containers/BottomMiddleContainer.tsx
  client/src/ui/layouts/Onboarding.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#710 cost cycle fix
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
Labels: enhancement, Review effort [1-5]: 3

#712 Production client fixes
  client/src/ui/components/resources/ResourceChip.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#716 show transaction status component above all others
  client/src/ui/modules/transactions/Transactions.tsx
Labels: enhancement, Review effort [1-5]: 1

#717 only show relevant part of failed tx error msg
  client/src/ui/modules/transactions/Transactions.tsx
Labels: enhancement, Review effort [1-5]: 3

#718 fix store capacity bug
  client/src/dojo/modelManager/ProductionManager.ts
Labels: Review effort [1-5]: 2, Bug fix

#725 open bank module when click bank
  client/src/hooks/notifications/useHyperstructureNotification.tsx
  client/src/hooks/notifications/useNotifications.tsx
  client/src/hooks/store/_dataStore.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/hooks/store/useRefreshHyperstructure.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/ui/components/HooksComponent.tsx
  client/src/ui/components/models/buildings/hyperstructures/HyperstructureFinished.tsx
  client/src/ui/components/models/buildings/hyperstructures/HyperstructureFinishedLowpoly.tsx
  client/src/ui/components/models/buildings/hyperstructures/HyperstructureHalf.tsx
  client/src/ui/components/models/buildings/hyperstructures/HyperstructureStarted.tsx
  client/src/ui/components/models/buildings/worldmap/Bank1.tsx
  client/src/ui/components/models/buildings/worldmap/Bank2.tsx
  client/src/ui/components/models/buildings/worldmap/Banks.tsx
  client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#726 Fix rerenders
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/models/buildings/worldmap/Castles.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx
  client/src/ui/modules/assistant/Assistant.tsx
  client/src/ui/modules/banking/Banks.tsx
  client/src/ui/modules/construction/Construction.tsx
  client/src/ui/modules/entity-details/EntityDetails.tsx
  client/src/ui/modules/events/Events.tsx
  client/src/ui/modules/hyperstructures/Hyperstructures.tsx
  client/src/ui/modules/leaderboard/LeaderBoard.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/questing/Questing.tsx
  client/src/ui/modules/resources/Resources.tsx
  client/src/ui/modules/settings/Settings.tsx
  client/src/ui/modules/trade/Trading.tsx
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#727 fix bugs
  client/src/hooks/helpers/useTrade.tsx
  client/src/ui/components/list/RealmListBoxes.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#728 config package rework
  client/src/dojo/modelManager/ProductionManager.ts
  client/src/hooks/helpers/useStructures.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/hooks/notifications/generateNotifications.tsx
  client/src/hooks/store/useBlockchainStore.tsx
  client/src/ui/components/cityview/realm/trade/AcceptOffer.tsx
  client/src/ui/components/cityview/realm/trade/DirectOffers/DirectOffersExplorerPopup.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/trading/Marketplace.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  config/.gitignore
  config/README.md
  config/index.ts
  config/package.json
  config/tsconfig.json
  contracts/scripts/set_config.sh
  pnpm-lock.yaml
  pnpm-workspace.yaml
  readme.md
  scripts/indexer.sh
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/constants/index.ts
  sdk/packages/eternum/src/constants/labor.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/constants/time.ts
  sdk/packages/eternum/src/constants/travel.ts
  sdk/packages/eternum/src/index.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#730 construction polish
  client/src/hooks/helpers/useQuests.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/elements/ResourceCost.tsx
  client/src/ui/elements/Tooltip.tsx
  client/src/ui/modules/construction/Construction.tsx
  config/index.ts
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 3

#733 Fix animation
  client/src/dojo/createSystemCalls.ts
  client/src/hooks/helpers/useExplore.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/hooks/helpers/useTravel.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/transport/contracts/travel_systems.cairo
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#734 Construction polish
  client/src/ui/components/models/buildings/worldmap/Castles.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/elements/Button.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#735 quest
  client/src/hooks/helpers/useQuests.tsx
  client/src/ui/components/hints/HintBox.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#736 Resource tweaks
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/components/trading/Marketplace.tsx
  client/src/ui/elements/ResourceCost.tsx
  client/src/ui/modules/resources/Resources.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/constants.cairo
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/buildings.ts
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#737 fix config capacity
  sdk/packages/eternum/src/config/index.ts
Labels: enhancement, Review effort [1-5]: 2

#738 Bank fees
  client/src/dojo/createUpdates.ts
  client/src/dojo/events/bankEventQueries.ts
  client/src/hooks/store/useBankStore.tsx
  client/src/ui/components/HooksComponent.tsx
  client/src/ui/components/bank/BankStats.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/src/systems/bank/contracts/swap_systems.cairo
  sdk/packages/eternum/src/constants/events.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#746 fix precision bug with cost
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
Labels: Review effort [1-5]: 2, bug_fix

#747 fix: coordinates mismatch
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/ui/components/construction/BigHexBiome.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/utils/utils.tsx
  sdk/packages/eternum/src/constants/hex.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#750 fix: switch positions of structures and battles in Location details OSWindow
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
Labels: enhancement, Review effort [1-5]: 1

#758 Army menu
  client/src/ui/components/models/buildings/worldmap/Castles.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#752 fix pillage history not showing + improve layout
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/military/Battle.tsx
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#759 Combat pillage fixes
  client/src/ui/components/military/Battle.tsx
  contracts/src/models/loyalty.cairo
  contracts/src/systems/combat/contracts.cairo
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#761 bug fixes and ux improvements
  client/public/images/buildings/construction/dragonhide.png
  client/public/images/buildings/construction/forge.png
  client/public/images/buildings/construction/lumber_mill.png
  client/public/sound/buildings/lumber_mill.mp3
  client/src/hooks/store/_buildModeStore.tsx
  client/src/hooks/useUISound.tsx
  client/src/ui/components/construction/BigHexBiome.tsx
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/utils/Camera.tsx
  client/src/ui/utils/utils.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#756 feat: Client + contracts: disallow user to create offer if amount of resource is 0
  client/src/ui/components/cityview/realm/trade/FastCreateOffer.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/testing/mint_resource.sh
  contracts/src/systems/trade/contracts/trade_systems.cairo
  contracts/src/systems/trade/tests/trade_systems_tests/create_order.cairo
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#762 fix refresh bug + small refactor
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
Labels: enhancement, Review effort [1-5]: 2

#764 show missing balance in red
  client/src/ui/elements/ResourceCost.tsx
Labels: enhancement, Review effort [1-5]: 2

#765 prevent from building if not enough resource for consumption (relates…
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
Labels: Review effort [1-5]: 2, bug_fix

#770 feat: remove magic multipliers from UI and set them in config
  client/src/dojo/modelManager/ProductionManager.ts
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/elements/ResourceCost.tsx
  contracts/data/labor_cost/labor_costs.csv
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#768 clean
  client/src/data/banks.json
  client/src/data/geodata/hex/bankHexPositions.json
  client/src/data/geodata/hex/biomes.js
  client/src/data/geodata/hex/generateAndSaveMap.js
  client/src/data/geodata/hex/getBiome.js
  client/src/data/geodata/hex/getBiomeWithCenter.js
  client/src/data/geodata/hex/getBiomeWithCliffs.js
  client/src/data/geodata/hex/getBiomeWithParts.js
  client/src/data/geodata/hex/hyperstructuresHexPositions.json
  client/src/data/geodata/hex/params.js
  client/src/data/geodata/hex/seedsnoise.js
  client/src/data/geodata/hex/snoise.js
  client/src/data/guilds.ts
  contracts/.DS_Store
  contracts/data/labor_cost/labor_costs.csv
  contracts/scripts/computeAuctionPrice.js
  contracts/scripts/computeResourceProbs.js
  contracts/scripts/config/constants.js
  contracts/scripts/config/generateBankCommands.js
  contracts/scripts/config/generateBuildingCosts.js
  contracts/scripts/config/generateHyperstructureCommands.js
  contracts/scripts/config/generateInitialAmounts.js
  contracts/scripts/config/generateLaborCostCommands.js
  contracts/scripts/config/generateLevelingCommands.js
  contracts/scripts/env_variables.sh
  contracts/scripts/labor/build_labor.sh
  contracts/scripts/labor/harvest_labor.sh
  contracts/scripts/scenarios/demo.sh
  contracts/scripts/scenarios/labor/1.sh
  contracts/scripts/scenarios/mint_basic_resources.sh
  contracts/scripts/scenarios/mint_realms.sh
  contracts/scripts/scenarios/mint_resources.sh
  contracts/scripts/scenarios/trade/1.sh
  contracts/scripts/set_admin_bank.sh
  contracts/scripts/set_config.sh
  contracts/scripts/testing/mint_realm.sh
  contracts/scripts/trade/attach_caravan.sh
  contracts/scripts/trade/claim_order.sh
  contracts/scripts/trade/make_lords_orders.sh
  contracts/scripts/trade/make_order.sh
  contracts/scripts/trade/marketMaking.mjs
  contracts/scripts/trade/take_order.sh
  contracts/scripts/transport/create_caravan.sh
  contracts/scripts/transport/create_free_transport_unit.sh
  readme.md
  scripts/deploy.sh
  scripts/indexer.sh
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#767 show useless consumption
  client/src/dojo/modelManager/ProductionManager.ts
  client/src/ui/components/resources/ResourceChip.tsx
Labels: enhancement, Review effort [1-5]: 3

#771 Fix bugs
  client/src/dojo/createUpdates.ts
  client/src/dojo/events/createEventSubscription.ts
  client/src/hooks/helpers/useHyperstructure.tsx
  client/src/hooks/useUISound.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#776 Resource menu
  client/public/images/buildings/thumb/scale.png
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useResources.tsx
  client/src/ui/components/cityview/realm/trade/FastCreateOffer.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/ArmyPanel.tsx
  client/src/ui/components/navigation/SideBar.tsx
  client/src/ui/components/resources/DepositResources.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/components/resources/ResourceWeight.tsx
  client/src/ui/components/trading/ResourceArrivals.tsx
  client/src/ui/components/trading/TransferBetweenEntities.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/containers/BaseContainer.tsx
  client/src/ui/elements/Button.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  client/src/ui/modules/trade/Trading.tsx
  client/tailwind.config.js
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  readme.md
  scripts/indexer.sh
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#778 miltary management
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/elements/Button.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/elements/TextInput.tsx
  client/src/ui/modules/onboarding/Steps.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#779 destroy building properly
  contracts/src/models/buildings.cairo
Labels: Review effort [1-5]: 2, bug_fix

#780 feat: destroy building button + scale exploration costs
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/elements/BaseThreeTooltip.tsx
  client/src/ui/elements/DojoHtml.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#781 add in time till depleation
  client/src/dojo/modelManager/ProductionManager.ts
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/elements/BaseThreeTooltip.tsx
  client/src/ui/elements/Button.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/elements/TextInput.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  client/src/ui/utils/utils.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#782 styles
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#783 feat: hexception clouds & destroy sounds
  client/public/sound/buildings/destroy_stone.mp3
  client/public/sound/buildings/destroy_wooden.mp3
  client/src/hooks/useUISound.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/modules/scenes/MainScene.tsx
Labels: enhancement, Review effort [1-5]: 3

#784 enh: Change weight deduct assert message to be more explicit
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/manifests/prod/manifest.json
  contracts/manifests/prod/manifest.toml
  contracts/src/models/weight.cairo
Labels: enhancement, Review effort [1-5]: 3

#786 feat: Add base population to config
  config/index.ts
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/manifests/prod/manifest.json
  contracts/manifests/prod/manifest.toml
  contracts/src/constants.cairo
  contracts/src/models/buildings.cairo
  contracts/src/models/config.cairo
  contracts/src/models/population.cairo
  contracts/src/systems/config/contracts.cairo
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4

#789 feat: wolrd map background
  client/hex/index.html
  client/index.html
  client/map/index.html
  client/public/textures/paper/worldmap-bg.png
  client/src/ui/components/models/biomes/HexGrid.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  scripts/indexer.sh
Labels: documentation, enhancement, Review effort [1-5]: 4, Bug fix

#791 nav
  client/public/images/buildings/thumb/question.png
  client/src/main.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/EntitiesArmyTable.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/containers/BaseContainer.tsx
  client/src/ui/containers/LeftMiddleContainer.tsx
  client/src/ui/containers/RightMiddleContainer.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/elements/Select.tsx
  client/src/ui/elements/Tooltip.tsx
  client/src/ui/elements/tab/tabs.tsx
  client/src/ui/modules/entity-details/EntityDetails.tsx
  client/src/ui/modules/military/Military.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: documentation, enhancement, Review effort [1-5]: 4, Bug fix

#793 armies, buildings, styles, market
  client/public/images/buildings/thumb/settings.png
  client/public/images/icons/archer.png
  client/public/images/icons/knight.png
  client/public/images/icons/paladin.png
  client/src/hooks/store/_mapStore.tsx
  client/src/ui/components/ModalContainer.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/models/buildings/worldmap/Castles.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/ui/components/worldmap/hexagon/HoveredHexes.tsx
  client/src/ui/components/worldmap/leaderboard/PlayersLeaderboard.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/elements/ResourceIcon.tsx
  client/src/ui/elements/Select.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
  sdk/packages/eternum/src/constants/resources.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#799 styles
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useQuests.tsx
  client/src/hooks/helpers/useResources.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/hints/HintBox.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/resources/DepositResources.tsx
  client/src/ui/components/resources/InventoryResources.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/trading/ResourceArrivals.tsx
  client/src/ui/components/worldmap/realms/RealmListItem.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: documentation, enhancement, Review effort [1-5]: 4, Bug fix

#801 fix: fixed camera angle for worldmap
  client/src/ui/utils/Camera.tsx
Labels: Review effort [1-5]: 2, Bug fix

#804 Shards mines
  client/src/dojo/contractComponents.ts
  client/src/hooks/helpers/useEntities.tsx
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/hooks/store/useRealmStore.tsx
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/models/buildings/worldmap/Banks.tsx
  client/src/ui/components/models/buildings/worldmap/ShardsMines.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
  contracts/scripts/system_models.json
  contracts/src/models/buildings.cairo
  contracts/src/models/config.cairo
  contracts/src/models/structure.cairo
  contracts/src/systems/buildings/contracts.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  contracts/src/systems/map/tests.cairo
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, tests, Bug fix

#805 Structures models
  client/src/hooks/helpers/useStructures.tsx
  client/src/hooks/store/_buildModeStore.tsx
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/components/structures/construction/StructurePreview.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#806 Raschel/hyper
  client/public/models/buildings/hyperstructure.glb
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/list/EntityList.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/components/structures/construction/StructurePreview.tsx
  client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx
  client/src/ui/modules/hyperstructures/Hyperstructures.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#812 UI polish
  client/src/ui/components/construction/GroundGrid.tsx
  client/src/ui/components/worldmap/BannerFlag.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/utils/Camera.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#807 add structure info in EntityDetails
  client/src/hooks/helpers/useStructures.tsx
  client/src/ui/components/military/Battle.tsx
  client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
  client/src/ui/components/worldmap/realms/RealmListItem.tsx
  client/src/ui/components/worldmap/structures/StructureListItem.tsx
Labels: enhancement, Review effort [1-5]: 2, other

#816 fix biomes + middle building
  client/src/ui/components/construction/BigHexBiome.tsx
  client/src/ui/components/construction/BuildArea.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/modules/scenes/HexceptionViewScene.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#818 feat: small ux improvements
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#817 Fix names
  client/src/hooks/helpers/useRealm.tsx
  client/src/ui/modules/onboarding/Steps.tsx
  client/src/ui/utils/utils.tsx
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#824 feat: various features
  client/src/dojo/createUpdates.ts
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/hooks/store/useLeaderBoardStore.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hyperstructures/HyperstructurePanel.tsx
  client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx
  client/src/ui/components/models/buildings/worldmap/Structures.tsx
  client/src/ui/elements/NumberInput.tsx
  client/src/ui/modules/hyperstructures/Hyperstructures.tsx
  sdk/packages/eternum/src/constants/buildings.ts
  sdk/packages/eternum/src/utils/index.ts
Labels: enhancement, Review effort [1-5]: 4, tests

#826 fix subscription
  client/src/hooks/store/_mapStore.tsx
Labels: Review effort [1-5]: 3, Bug fix

#832 fix: buffer polyfill
  client/package.json
  client/src/main.tsx
  pnpm-lock.yaml
Labels: Review effort [1-5]: 2, Bug fix, Dependencies

#833 feat: UI and smart contracts of stamina
  client/src/dojo/contractComponents.ts
  client/src/hooks/helpers/useResources.tsx
  client/src/hooks/helpers/useStamina.tsx
  client/src/hooks/notifications/generateNotifications.tsx
  client/src/hooks/store/useBlockchainStore.tsx
  client/src/hooks/store/useLeaderBoardStore.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/utils/utils.tsx
  config/index.ts
  contracts/Scarb.lock
  contracts/Scarb.toml
  contracts/scripts/system_models.json
  contracts/src/constants.cairo
  contracts/src/models.cairo
  contracts/src/models/buildings.cairo
  contracts/src/models/config.cairo
  contracts/src/models/production.cairo
  contracts/src/models/resources.cairo
  contracts/src/models/stamina.cairo
  contracts/src/models/tick.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/config/contracts.cairo
  contracts/src/systems/map/contracts.cairo
  contracts/src/systems/map/tests.cairo
  contracts/src/systems/transport/contracts/donkey_systems.cairo
  contracts/src/systems/transport/contracts/travel_systems.cairo
  contracts/src/systems/transport/tests/travel_systems_tests.cairo
  contracts/src/utils/testing.cairo
  pnpm-lock.yaml
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/global.ts
  sdk/packages/eternum/src/constants/index.ts
  sdk/packages/eternum/src/constants/resources.ts
  sdk/packages/eternum/src/provider/index.ts
  sdk/packages/eternum/src/types/provider.ts
Labels: enhancement, Review effort [1-5]: 4, tests, configuration changes

#835 fix build
  client/src/hooks/helpers/useCombat.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/components/worldmap/leaderboard/OrdersLeaderboard.tsx
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#837 fix: UI bugs
  .gitignore
  client/src/hooks/helpers/useBuildings.tsx
  client/src/hooks/store/_buildModeStore.tsx
  client/src/ui/components/construction/ExistingBuildings.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/elements/ResourceCost.tsx
  client/src/ui/modules/scenes/MainScene.tsx
  client/src/ui/utils/realms.tsx
  client/src/ui/utils/utils.tsx
  contracts/.gitignore
  contracts/manifests/dev/manifest.json
  contracts/manifests/dev/manifest.toml
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#831 Armies world map
  client/src/hooks/helpers/useCombat.tsx
  client/src/hooks/store/_mapStore.tsx
  client/src/types/index.ts
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/components/models/armies/WarriorModel.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/armies/ArmyMenu.tsx
  client/src/ui/components/worldmap/hexagon/ActionInfo.tsx
  client/src/ui/components/worldmap/hexagon/FixedHexagonInformation.tsx
  client/src/ui/components/worldmap/hexagon/HexLayers.tsx
  client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx
  client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
  client/src/ui/components/worldmap/hexagon/utils.tsx
  client/src/ui/components/worldmap/traveling/TravelPopup.tsx
  client/src/ui/elements/BaseThreeTooltip.tsx
  client/src/ui/elements/DojoHtml.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/scenes/WorldMapScene.tsx
  client/tailwind.config.js
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#840 [client] new sounds, ui fixes
  client/public/sound/events/battle_defeat.mp3
  client/public/sound/events/battle_victory.mp3
  client/src/hooks/useUISound.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/elements/BaseThreeTooltip.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#841 feat: worldmap clouds
  client/src/ui/modules/scenes/MainScene.tsx
Labels: enhancement, Review effort [1-5]: 3

#838 fix army info lag on hover + remove useCombat
  client/src/hooks/helpers/useCombat.tsx
  client/src/ui/components/worldmap/armies/Armies.tsx
  client/src/ui/components/worldmap/armies/Army.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix
