Repository BibliothecaDAO/eternum, pull requests merged in 2024-08, with the labels that each got.

#1145 fix: balance resource view
  client/src/dojo/modelManager/ProductionManager.ts
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/resources/ResourceChip.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/modules/military/battle-view/TopScreenView.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix, formatting

#1117 fix army weight when exploring, add weigh + capacity in UI
  client/src/dojo/modelManager/__tests__/__mock__.ts
  client/src/hooks/helpers/useArmies.tsx
  client/src/ui/components/entities/Entity.tsx
  client/src/ui/components/military/ArmyChip.tsx
  client/src/ui/components/military/ArmyList.tsx
  client/src/ui/components/quest/QuestInfo.tsx
  client/src/ui/components/trading/MarketOrderPanel.tsx
  client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx
  client/src/ui/components/worldmap/hexagon/ActionInfo.tsx
  client/src/ui/components/worldmap/hexagon/useTravelPath.tsx
  client/src/ui/components/worldmap/hexagon/utils.tsx
  client/src/ui/elements/ArmyCapacity.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  sdk/packages/eternum/src/config/index.ts
  sdk/packages/eternum/src/constants/structures.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1152 fix: subscriptions with wildcard pattern matching
  client/src/dojo/setup.ts
Labels: Review effort [1-5]: 2, Bug fix

#1151 Enh/cleanup
  .knip.json
  client/src/dojo/events/bankEventQueries.ts
  client/src/hooks/store/useBankStore.tsx
  client/src/hooks/useUISound.tsx
  client/src/types/index.ts
  client/src/ui/components/bank/BankEntityList.tsx
  client/src/ui/components/bank/BankStats.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/military/TroopChip.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/config.tsx
  client/src/ui/modules/military/battle-view/BattleDetails.tsx
  client/src/ui/utils/utils.tsx
Labels: enhancement, Review effort [1-5]: 2, miscellaneous

#1175 Remove skip tutorial button once done w/ quests
  client/src/ui/components/quest/QuestList.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1177 fix: modals not detecting click events
  client/src/hooks/helpers/useStamina.tsx
  client/src/ui/containers/BlankOverlayContainer.tsx
  client/src/ui/layouts/World.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1183 fixes #1160
  client/src/three/systems/SystemManager.ts
Labels: Review effort [1-5]: 2, Bug fix

#1184 fix: explored hex cache bug
  client/src/three/scenes/Worldmap.ts
  client/src/ui/containers/TopLeftContainer.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1182 Fix 1180
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/store/_threeStore.tsx
  client/src/three/components/ArmyManager.ts
  client/src/three/components/HighlightHexManager.ts
  client/src/three/scenes/HexagonScene.ts
  client/src/three/scenes/Hexception.ts
  client/src/three/scenes/Worldmap.ts
  client/src/three/systems/SystemManager.ts
  client/src/ui/utils/utils.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1181 feat: switch scenes
  client/src/hooks/store/useUIStore.tsx
  client/src/three/GameRenderer.ts
  client/src/three/SceneManager.ts
  client/src/three/components/Biome.ts
  client/src/three/components/BuildingPreview.ts
  client/src/three/components/InputManager.ts
  client/src/three/components/TransitionManager.tsx
  client/src/three/scenes/HexagonScene.ts
  client/src/three/scenes/Hexception.ts
  client/src/three/scenes/Worldmap.ts
  client/src/types/Position.ts
  client/src/types/index.ts
  client/src/ui/components/military/ArmyManagementCard.tsx
  client/src/ui/containers/TopMiddleContainer.tsx
  client/src/ui/modules/entity-details/EntityDetails.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/utils/utils.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1187 Fix 1176 + hexception refactoring
  client/src/dojo/modelManager/TileManager.ts
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/three/components/BuildingPreview.ts
  client/src/three/components/HighlightHexManager.ts
  client/src/three/components/InteractiveHexManager.ts
  client/src/three/scenes/HexagonScene.ts
  client/src/three/scenes/Hexception.ts
  client/src/three/scenes/Worldmap.ts
  client/src/three/scenes/constants.ts
  client/src/three/systems/types.ts
  client/src/ui/utils/utils.tsx
  sdk/packages/eternum/src/constants/hex.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1194 enh: Optimize react
  client/src/ui/components/worldmap/armies/ActionInfo.tsx
  client/src/ui/containers/BaseContainer.tsx
  client/src/ui/containers/BlankOverlayContainer.tsx
  client/src/ui/elements/CircleButton.tsx
  client/src/ui/elements/SecondaryPopup.tsx
  client/src/ui/elements/Tooltip.tsx
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/LoadingScreen.tsx
  client/src/ui/modules/military/battle-view/Battle.tsx
  client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
  client/src/ui/modules/onboarding/Steps.tsx
Labels: enhancement, Review effort [1-5]: 3

#1192 fix click firing after drag
  client/src/three/components/InputManager.ts
Labels: Review effort [1-5]: 2, Bug fix

#1191 Fix/models
  client/src/dojo/modelManager/ArmyMovementManager.ts
  client/src/three/components/StructureManager.ts
  client/src/three/scenes/Worldmap.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1203 fixes #1197
  client/src/three/scenes/Worldmap.ts
  contracts/manifests/dev/deployment/manifest.json
  contracts/manifests/dev/deployment/manifest.toml
Labels: Review effort [1-5]: 3, Bug fix, configuration changes

#1206 set preview building zustand state to null + add state to HexagonScene
  client/src/three/scenes/HexagonScene.ts
  client/src/three/scenes/Hexception.ts
  client/src/three/scenes/Worldmap.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1208 fix #1201 army selection issue
  client/src/three/components/InputManager.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1199 Fix 1190
  client/src/dojo/modelManager/TileManager.ts
  client/src/hooks/store/_threeStore.tsx
  client/src/three/scenes/HexagonScene.ts
  client/src/three/scenes/Hexception.ts
  client/src/three/scenes/Worldmap.ts
  client/src/three/scenes/constants.ts
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/modules/entity-details/BuildingEntityDetails.tsx
  client/src/ui/modules/entity-details/CombatEntityDetails.tsx
  client/src/ui/modules/entity-details/EntityDetails.tsx
  sdk/packages/eternum/src/constants/structures.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#1212 Fix label translate
  client/src/three/components/ArmyManager.ts
  client/src/three/components/LabelManager.ts
Labels: enhancement, Review effort [1-5]: 2

#1205 Enable build hyperstructure
  client/src/dojo/modelManager/TileManager.ts
  client/src/hooks/helpers/useHexPosition.tsx
  client/src/hooks/helpers/useRealm.tsx
  client/src/hooks/helpers/useTrade.tsx
  client/src/hooks/store/useRealmStore.tsx
  client/src/hooks/store/useUIStore.tsx
  client/src/three/components/StructureManager.ts
  client/src/three/components/StructurePreview.ts
  client/src/three/scenes/Hexception.ts
  client/src/three/scenes/Worldmap.ts
  client/src/three/scenes/constants.ts
  client/src/ui/components/cityview/realm/SettleRealmComponent.tsx
  client/src/ui/components/construction/SelectPreviewBuilding.tsx
  client/src/ui/components/hyperstructures/HyperstructurePanel.tsx
  client/src/ui/components/structures/construction/StructureConstructionMenu.tsx
  client/src/ui/components/trading/MarketModal.tsx
  client/src/ui/components/worldmap/armies/ActionInfo.tsx
  client/src/ui/layouts/World.tsx
  client/src/ui/modules/navigation/BottomNavigation.tsx
  client/src/ui/modules/navigation/LeftNavigationModule.tsx
  client/src/ui/modules/navigation/RightNavigationModule.tsx
  client/src/ui/modules/navigation/TopMiddleNavigation.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#1217 Add model to BuildingType.none to fix model loading
  client/src/three/scenes/constants.ts
Labels: Review effort [1-5]: 1, Bug fix

#1218 Fix dojo update
  client/src/main.tsx
  client/src/three/GameRenderer.ts
  client/src/ui/modules/onboarding/Steps.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1219 placeholder models
  client/src/three/scenes/constants.ts
Labels: enhancement, Review effort [1-5]: 2

#1226 prevent select enemy army
  client/src/three/components/ArmyManager.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#1238 remove dojo update
  client/src/main.tsx
Labels: enhancement

#1228 Dynamic hp models
  client/public/models/buildings/hyperstructure-half-transformed.glb
  client/public/models/buildings/hyperstructure.glb
  client/public/models/buildings/hyperstructure_final.glb
  client/public/models/buildings/hyperstructure_half.glb
  client/public/models/buildings/hyperstructure_init.glb
  client/src/three/components/BuildingPreview.ts
  client/src/three/components/InstancedBuilding.tsx
  client/src/three/components/InstancedModel.tsx
  client/src/three/components/StructureManager.ts
  client/src/three/components/StructurePreview.ts
  client/src/three/scenes/Worldmap.ts
  client/src/three/scenes/constants.ts
  client/src/three/systems/SystemManager.ts
  client/src/three/systems/types.ts
Labels: enhancement, Review effort [1-5]: 4

#1216 contracts: allow realm capture
  .github/workflows/knip.yml
  .github/workflows/lint.yml
  .github/workflows/test-client.yml
  .github/workflows/test-contracts.yml
  .tool-versions
  client/src/dojo/modelManager/BattleManager.ts
  client/src/dojo/modelManager/__tests__/BattleManager.test.ts
  client/src/hooks/helpers/useArmies.tsx
  client/src/hooks/helpers/useEntities.tsx
  client/src/three/GameRenderer.ts
  client/src/three/SceneManager.ts
  client/src/three/systems/SystemManager.ts
  client/src/ui/modules/entity-details/CombatEntityDetails.tsx
  client/src/ui/modules/entity-details/Entities.tsx
  contracts/src/models/buildings.cairo
  contracts/src/systems/combat/contracts.cairo
  contracts/src/systems/map/tests.cairo
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, Bug fix
